webpage final version.html
Today
5:27 pm
Y
Yee Kam Chan renamed an item
HTML
webpage final version.html
webpage.html
5:27 pm
Y
Yee Kam Chan uploaded an item
HTML
webpage.html
<!DOCTYPE html>

<html> 

<head>

<title>Bilingual Legal Dictionary</title>

<script type="text/JavaScript">

abList = [ 
["一方當事人","party / 一方当事人 / yī fāng dāng shì rén / yat1fong1dong1si6yan4"],
["一致表決","unanimous vote / 一致表决 / yī zhì biǎo jué / jat1zi3biu2kyut3"],
["一致裁決","unanimous verdict / 一致裁决 / yī zhì cái jué / jat1zi3coi4kyut3"],
["一般代表","general proxy / 一般代表 / yī bān dài biǎo / jat1bun1doi6biu2"],
["一般出庭發言權","general right of audience / 一般出庭发言权 / yī bān chū tíng fā yán quán / jat1bun1ceot1ting4faat3jin4kyun4"],
["一般司法管轄權","ordinary jurisdiction / 一般司法管辖权 / yī bān sī fǎ guǎn xiá quán / jat1bun1si1faat3gun2hat6kyun4"],
["一般地或在任何個別情況下","generally or in any particular case / 一般地或在任何个别情况下 / yī bān dì huò zài rèn hé gè bié qíng kuàng xià / jat1bun1dei6waak6zoi6jam6ho4go3bit6cing4fong3haa6"],
["一般安全證明書","general safety certificate / 一般安全证明书 / yī bān ān quán zhèng míng shū / jat1bun1on1cyun4zing3ming4syu1"],
["一般保稅倉","general bonded warehouse / 一般保税仓 / yī bān bǎo shuì cāng / jat1bun1bou2seoi3cong1"],
["一般指定受益的權力","general power of appointment / 一般指定受益的权力 / yī bān zhǐ dìng shòu yì de quán lì / jat1bun1zi2ding6sau6jik1dik1kyun4lik6"],
["一般授權","general authority / 一般授权 / yī bān shòu quán / jat1bun1sau6kyun4"],
["一般授權書","general power of attorney / 一般授权书 / yī bān shòu quán shū / jat1bun1sau6kyun4syu1"],
["一般寬免","general waiver / 一般宽免 / yī bān kuān miǎn / jat1bun1fun1min5"],
["一般遺產管理人","general administrator / 一般遗产管理人 / yī bān yí chǎn guǎn lǐ rén / jat1bun1wai4caan2gun2lei5jan4"],
["一般謹慎責任","common duty of care / 一般谨慎责任 / yī bān jǐn shèn zé rèn / jat1bun1gan2san6zaak3jam6"],
["一開始","ab initio / 一开始 / yī kāi shǐ / jat1hoi1ci2"],
["一經循公訴程序定罪","on conviction upon indictment / 一经循公诉程序定罪 / yī jīng xún gōng sù chéng xù dìng zuì / jat1ging1ceon4gung1sou3cing4zeoi6ding6zeoi6"],
["一整筆款項","lump sum / 一整笔款项 / yī zhěng bǐ kuǎn xiàng / jat1zing2bat1fun2hong6"],
["一般代表","general proxy / 一般代表 / yī bān dài biăo / jat1 bun1 doi6 biu2"],
["丁屋土地","small house holding / 丁屋土地 / dīng wū tǔ dì / ding1uk1tou2dei6"],
["丁屋批租約","small house grant / 丁屋批租约 / dīng wū pī zū yuē / ding1uk1pai1zou1joek3"],
["三分之二大多數","majority of two-thirds / 三分之二大多数 / sān fēn zhī 'èr dà duō shù / saam1fan6zi1ji6daai6do1sou3"],
["三合會","triad society / 三合会 / sān hé huì / saam1hap6wui2"],
["三合會社團","triad society / 三合会社团 / sān hé huì shè tuán / saam1hap6wui2se5tyun4"],
["上一級業主","superior landlord / 上一级业主 / shàng yī jí yè zhǔ / soeng6jat1kap1jip6zyu2"],
["上市","listed / 上市 / shàng shì / soeng6si5"],
["上市公司","listed company / 上市公司 / shàng shì gōng sī / soeng6si5gung1si1"],
["上市股份","listed shares / 上市股份 / shàng shì gǔ fèn / soeng6si5gu2fan6"],
["上市證券","listed securities / 上市证券 / shàng shì zhèng quàn / soeng6si5zing3gyun3/hyun3"],
["上訴","appeal / 上诉 / shàng sù / soeng6sou3"],
["上訴人","appellant / 上诉人 / shàng sù rén / soeng6sou3jan4"],
["上訴司法管轄權","appellate jurisdiction / 上诉司法管辖权 / shàng sù sī fǎ guǎn xiá quán / soeng6sou3si1faat3gun2hat6kyun4"],
["上訴用案件呈述的方式","appeal by way of a case stated / 上诉用案件呈述的方式 / shàng sù yòng àn jiàn chéng shù de fāng shì / soeng6sou3jung6on3gin6cing4seot6dik1fong1sik1"],
["上訴委員會","Appeal Committee / 上诉委员会 / shàng sù wěi yuán huì / soeng6sou3wai2jun4wui2"],
["上訴法庭","the Court of Appeal / 上诉法庭 / shàng sù fǎ tíng / soeng6sou3faat3ting4"],
["上訴法庭法官","Justice of Appeal / 上诉法庭法官 / shàng sù fǎ tíng fǎ guān / soeng6sou3faat3ting4faat3gun1"],
["上訴法庭庭長","president of the Court of Appeal / 上诉法庭庭长 / shàng sù fǎ tíng tíng zhǎng / soeng6sou3faat3ting4ting4zoeng2"],
["上訴法庭副庭長","vice-presidents of the Court of Appeal / 上诉法庭副庭长 / shàng sù fǎ tíng fù tíng zhǎng / soeng6sou3faat3ting4fu3ting4zoeng2"],
["上訴的目的不能達致","appeal frustrated / 上诉的目的不能达致 / shàng sù de mù dì bù néng dá zhì / soeng6sou3dik1muk6dik1bat1nang4daat6zi3"],
["上訴的許可","leave to appeal / 上诉的许可 / shàng sù de xǔ kě / soeng6sou3dik1heoi2ho2"],
["上訴的權利","right of appeal / 上诉的权利 / shàng sù de quán lì / soeng6sou3dik1kyun4lei6"],
["上訴案件聆訊表","list of appeals / 上诉案件聆讯表 / shàng sù àn jiàn líng xùn biǎo / soeng6sou3on3gin6ling4seon3biu2"],
["上訴被撤回","appeal withdrawn / 上诉被撤回 / shàng sù bèi chè huí / soeng6sou3bei6/pei5cit3wui4"],
["上訴動議通知書","notice of motion of appeal / 上诉动议通知书 / shàng sù dòng yì tōng zhī shū / soeng6sou3dung6ji5tung1zi1syu1"],
["上訴理由","grounds of appeal / 上诉理由 / shàng sù lǐ yóu / soeng6sou3lei5jau4"],
["上訴許可申請書","application for leave to appeal / 上诉许可申请书 / shàng sù xǔ kě shēn qǐng shū / soeng6sou3heoi2ho2san1cing2syu1"],
["上訴通知","notice of appeal / 上诉通知 / shàng sù tōng zhī / soeng6sou3tung1zi1"],
["上訴通知書","notice of appeal / 上诉通知书 / shàng sù tōng zhī shū / soeng6sou3tung1zi1syu1"],
["上訴援助證書","appeal aid certificate / 上诉援助证书 / shàng sù yuán zhù zhèng shū / soeng6sou3wun4zo6zing3syu1"],
["上訴登記冊","Register of Appeals / 上诉登记册 / shàng sù dēng jì cè / soeng6sou3dang1gei3caak3"],
["上訴當事人","party to the appeal / 上诉当事人 / shàng sù dāng shì rén / soeng6sou3dong1si6jan4"],
["上訴摘要","memorandum of appeal / 上诉摘要 / shàng sù zhāi yào / soeng6sou3zaak6jiu3"],
["上訴駁回","appeal dismissed / 上诉驳回 / shàng sù bó huí / soeng6sou3bok3wui4"],
["上訴審訊表","list of appeals / 上诉审讯表 / shàng sù shěn xùn biǎo / soeng6sou3sam2seon3biu2"],
["上訴審裁處","appellate tribunal / 上诉审裁处 / shàng sù shěn cái chǔ / soeng6sou3sam2coi4cyu5"],
["上訴獲得解決","appeal disposed of / 上诉获得解决 / shàng sù huò dé jiě jué / soeng6sou3wok6dak1gaai2kyut3"],
["上訴權","right of appeal / 上诉权 / shàng sù quán / soeng6sou3kyun4"],
["上課令","attendance order / 上课令 / shàng kè lìng / soeng6fo3ling6"],
["下一級業主","inferior landlord / 下一级业主 / xià yī jí yè zhǔ / haa6jat1kap1jip6zyu2"],
["下一停靠港","next port of call / 下一停靠港 / xià yī tíng kào gǎng / haa6jat1ting4kaau3gong2"],
["下令","order / 下令 / xià lìng / haa6ling6"],
["下毒","poisoning / 下毒 / xià dú / haa6duk6"],
["下級法庭","inferior court / 下级法庭 / xià jí fǎ tíng / haa6kap1faat3ting4"],
["下級法庭","the court below / 下级法庭 / xià jí fǎ tíng / haa6kap1faat3ting4"],
["下級法院","inferior court / 下级法院 / xià jí fǎ yuàn / haa6kap1faat3jun6/jun2"],
["不人道","inhumane / 不人道 / bù rén dào / bat1jan4dou6"],
["不小心或不謹慎","want of the due care or caution / 不小心或不谨慎 / bù xiǎo xīn huò bù jǐn shèn / bat1siu2sam1waak6bat1gan2san6"],
["不公平","inequitable / 不公平 / bù gōng píng / bat1gung1ping4"],
["不公平的手法","unfair tactics / 不公平的手法 / bù gōng píng de shǒu fǎ / bat1gung1ping4dik1sau2faat3"],
["不公正的情況","a miscarriage of justice / 不公正的情况 / bù gōng zhèng de qíng kuàng / bat1gung1zing3dik1cing4fong3"],
["不公開","in private / 不公开 / bù gōng kāi / bat1gung1hoi1"],
["不分割份數","undivided share / 不分割份数 / bù fēn gē fèn shù / bat1fan1got3fan6sou3"],
["不分割份額","undivided share / 不分割份额 / bù fēn gē fèn 'é / bat1fan1got3fan6ngaak6"],
["不付款而離去","making off without payment / 不付款而离去 / bù fù kuǎn ér lí qù / bat1fu6fun2ji4lei4heoi3"],
["不可抗力","force majeure / 不可抗力 / bù kě kàng lì / bat1ho2kong3lik6"],
["不可侵犯權","inviolability / 不可侵犯权 / bù kě qīn fàn quán / bat1ho2cam1faan6kyun4"],
["不可商售的貨品","unmerchantable goods / 不可商售的货品 / bù kě shāng shòu de huò pǐn / bat1ho2soeng1sau6dik1fo3ban2"],
["不可推翻地推定","conclusively presumed / 不可推翻地推定 / bù kě tuī fān dì tuī dìng / bat1ho2teoi1faan1dei6teoi1ding6"],
["不可推翻的證據","conclusive evidence / 不可推翻的证据 / bù kě tuī fān de zhèng jù / bat1ho2teoi1faan1dik1zing3geoi3"],
["不可閱的形式","non-legible form / 不可阅的形式 / bù kě yuè de xíng shì / bat1ho2jyut6dik1jing4sik1"],
["不可轉讓","non-assignable / 不可转让 / bù kě zhuǎn ràng / bat1ho2zyun3joeng6"],
["不再服務薪津","non-effective pay / 不再服务薪津 / bù zài fú wù xīn jīn / bat1zoi3fuk6mou6san1zeon1"],
["不同控罪","distinct charges / 不同控罪 / bù tóng kòng zuì / bat1tung4hung3zeoi6"],
["不合併","nonjoinder / 不合并 / bù hé bìng / bat1hap6bing3"],
["不合情理的作為","unconscionable act / 不合情理的作为 / bù hé qíng lǐ de zuò wéi / bat1hap6cing4lei5dik1zok3wai4"],
["不合理地","unreasonably / 不合理地 / bù hé lǐ dì / bat1hap6lei5dei6"],
["不合理的風險","undue risk / 不合理的风险 / bù hé lǐ de fēng xiǎn / bat1hap6lei5dik1fung1him2"],
["不合理的條款","unreasonable terms / 不合理的条款 / bù hé lǐ de tiáo kuǎn / bat1hap6lei5dik1tiu4fun2"],
["不在犯罪現場","alibi / 不在犯罪现场 / bù zài fàn zuì xiàn chǎng / bat1zoi6faan6zeoi6jin6coeng4"],
["不在犯罪現場詳情的通知","notice of particulars of the alibi / 不在犯罪现场详情的通知 / bù zài fàn zuì xiàn chǎng xiáng qíng de tōng zhī / bat1zoi6faan6zeoi6jin6coeng4coeng4cing4dik1tung1zi1"],
["不在訟案內的法律程序","proceeding not in a cause / 不在讼案内的法律程序 / bù zài sòng àn nèi de fǎ lǜ chéng xù / bat1zoi6zung6on3noi6dik1faat3leot6cing4zeoi6"],
["不在羈留中","at large / 不在羁留中 / bù zài jī liú zhōng / bat1zoi6gei1lau4zung1"],
["不守法","disobedience to law / 不守法 / bù shǒu fǎ / bat1sau2faat3"],
["不作為","/act of omission/ommision/ / 不作为 / bù zuò wéi / bat1zok3wai4/wai6"],
["不兌現","dishonour / 不兑现 / bù duì xiàn / bat1deoi3jin6"],
["不兌現的匯票","dishonoured bill / 不兑现的汇票 / bù duì xiàn de huì piào / bat1deoi3jin6dik1wui6piu3"],
["不利於","prejudice / 不利于 / bù lì yú / bat1lei6ju1"],
["不含實際惡意","without actual malice / 不含实际恶意 / bù hán shí jì è yì / bat1ham4sat6zai3ok3ji3"],
["不完整權益","partial interest / 不完整权益 / bù wán zhěng quán yì / bat1jun4zing2kyun4jik1"],
["不批准","disapprove / 不批准 / bù pī zhǔn / bat1pai1zeon2"],
["不良分子","undesirable person / 不良分子 / bù liáng fèn zǐ / bat1loeng4fan6zi2"],
["不良行為","malpractice / 不良行为 / bù liáng xíng wéi / bat1loeng4hang4wai4"],
["不依合法妾侍制度同居","live together in unlawful concubinage / 不依合法妾侍制度同居 / bù yī hé fǎ qiè shì zhì dù tóng jū / bat1ji1hap6faat3cip3si6zai3dou6tung4geoi1"],
["不具顯著特性的","of a non-distinctive character / 不具显著特性的 / bù jù xiǎn zhù tè xìng de / bat1geoi6hin2zoek3dak6sing3dik1"],
["不受歡迎入境者","undesirable immigrant / 不受欢迎入境者 / bù shòu huān yíng rù jìng zhě / bat1sau6fun1jing4jap6ging2ze2"],
["不受歡迎並涉及性的行徑","unwelcome conduct of a sexual nature / 不受欢迎并涉及性的行径 / bù shòu huān yíng bìng shè jí xìng de xíng jìng / bat1sau6fun1jing4bing6sip3kap6sing3dik1hang4ging3"],
["不受歡迎的性要求","unwelcome sexual advance / 不受欢迎的性要求 / bù shòu huān yíng de xìng yāo qiú / bat1sau6fun1jing4dik1sing3jiu3kau4"],
["不受歡迎的獲取性方面的好處的要求","unwelcome request for sexual favours / 不受欢迎的获取性方面的好处的要求 /  bù shòu huān yíng de huò qǔ xìng fāng miàn de hǎo chù de yāo qiú  /bat1sau6fun1jing4dik1wok6ceoi2sing3fong1min6dik1hou2cyu5dik1jiu3kau4"],
["不定期租契","lease at will / 不定期租契 / bù dìng qī zū qì / bat1ding6kei4zou1kai3"],
["不忠實行為","dishonesty / 不忠实行为 / bù zhōng shí xíng wéi / bat1zung1sat6hang4wai4"],
["不承認","non-admission / 不承认 / bù chéng rèn / bat1sing4jing6"],
["不承認通知書","notice of non-admission / 不承认通知书 / bù chéng rèn tōng zhī shū / bat1sing4jing6tung1zi1syu1"],
["不披露","non-disclosure / 不披露 / bù pī lù / bat1pei1lou6"],
["不服從上級","insubordination / 不服从上级 / bù fú cóng shàng jí / bat1fuk6cung4soeng6kap1"],
["不法作為","unlawful act / 不法作为 / bù fǎ zuò wéi / bat1faat3zok3wai4"],
["不知情","without knowledge / 不知情 / bù zhī qíng / bat1zi1cing4"],
["不知情地","innocently / 不知情地 / bù zhī qíng dì / bat1zi1cing4dei6"],
["不知情地取得","innocently acquired / 不知情地取得 / bù zhī qíng dì qǔ dé / bat1zi1cing4dei6ceoi2dak1"],
["不知情的第三者","innocent third party / 不知情的第三者 / bù zhī qíng de dì sān zhě / bat1zi1cing4dik1dai6saam1ze2"],
["不知情侵犯版權","innocent infringement of copyright / 不知情侵犯版权 / bù zhī qíng qīn fàn bǎn quán / bat1zi1cing4cam1faan6baan2kyun4"],
["不附帶條件的","absolute / 不附带条件的 / bù fù dài tiáo jiàn de / bat1fu6daai3tiu4gin6dik1"],
["不活動公司","dormant company / 不活动公司 / bù huó dòng gōng sī / bat1wut6dung6gung1si1"],
["不准","disallow / 不准 / bù zhǔn / bat1zeon2"],
["不容反悔法","estoppel / 不容反悔法 / bù róng fǎn huǐ fǎ / bat1jung4faan2fui3faat3"],
["不真誠","bad faith / 不真诚 / bù zhēn chéng / bat1zan1sing4"],
["不能強制執行","unenforceable / 不能强制执行 / bù néng qiáng zhì zhí xíng / bat1nang4koeng4zai3zap1hang4"],
["不能強制履行","unenforceable / 不能强制履行 / bù néng qiáng zhì lǚ xíng / bat1nang4koeng4zai3lei5hang4"],
["不能預知","not foreseen / 不能预知 / bù néng yù zhī / bat1nang4ju6zi1"],
["不能實行","inoperative / 不能实行 / bù néng shí xíng / bat1nang4sat6hang4"],
["不能廢止地有權","indefeasibly entitled / 不能废止地有权 / bù néng fèi zhǐ dì yǒu quán / bat1nang4fai3zi2dei6jau5kyun4"],
["不記名文書","bearer instrument / 不记名文书 / bù jì míng wén shū / bat1gei3ming4man4syu1"],
["不記名投票","/poll/secret ballot/ / 不记名投票 / bù jì míng tóu piào / bat1gei3ming4tau4piu3"],
["不記名投票方式","secret ballot / 不记名投票方式 / bù jì míng tóu piào fāng shì / bat1gei3ming4tau4piu3fong1sik1"],
["不記名提單","bearer bill / 不记名提单 / bù jì míng tí dān / bat1gei3ming4tai4daan1"],
["不記名債券","bearer bonds / 不记名债券 / bù jì míng zhài quàn / bat1gei3ming4zaai3gyun3/hyun3"],
["不記名債權證","bearer debentures / 不记名债权证 / bù jì míng zhài quán zhèng / bat1gei3ming4zaai3kyun4zing3"],
["不動產","immovable property / 不动产 / bù dòng chǎn / bat1dung6caan2"],
["不專業行為","unprofessional conduct / 不专业行为 / bù zhuān yè xíng wéi / bat1zyun1jip6hang4wai4"],
["不得以罰款代替","without the option of a fine / 不得以罚款代替 / bù dé yǐ fá kuǎn dài tì / bat1dak1ji5fat6fun2doi6tai3"],
["不符合資格","want of qualification / 不符合资格 / bù fú hé zī gé / bat1fu4hap6zi1gaak3"],
["不許公眾旁聽任何法律程序","exclusion of the public from any proceedings / 不许公众旁听任何法律程序 / bù xǔ gōng zhòng páng tīng rèn hé fǎ lǜ chéng xù / bat1heoi2gung1zung3pong4ting1jam6ho4faat3leot6cing4zeoi6"],
["不連商譽","without goodwill / 不连商誉 / bù lián shāng yù / bat1lin4soeng1ju6"],
["不雅","indecency / 不雅 / bù yǎ / bat1ngaa5"],
["不雅物品","indecent article / 不雅物品 / bù yǎ wù pǐn / bat1ngaa5mat6ban2"],
["不損害","without prejudice / 不损害 / bù sǔn hài / bat1syun2hoi6"],
["不當乾擾","undue interference / 不当干扰 / bù dàng gān rǎo / bat1dong3gon1jiu2"],
["不當地取得管有","wrongfully taken possession of / 不当地取得管有 / bù dàng dì qǔ dé guǎn yǒu / bat1dong3dei6ceoi2dak1gun2jau5"],
["不當作為","miscarriage / 不当作为 / bù dàng zuò wéi / bat1dong3zok3wai4/wai6"],
["不當使用職權","misuse of office / 不当使用职权 / bù dàng shǐ yòng zhí quán / bat1dong3si2/sai2jung6zik1kyun4"],
["不當延誤","undue delay / 不当延误 / bù dàng yán wù / bat1dong3jin4ng6"],
["不當的延遲","undue delay / 不当的延迟 / bù dàng de yán chí / bat1dong3dik1jin4ci4"],
["不當的舉止","unseemly manner / 不当的举止 / bù dàng de jǔ zhǐ / bat1dong3dik1geoi2zi2"],
["不當損害","undue detriment / 不当损害 / bù dàng sǔn hài / bat1dong3syun2hoi6"],
["不當影響","undue influence / 不当影响 / bù dàng yǐng xiǎng / bat1dong3jing2hoeng2"],
["不當遷移","wrongful removals / 不当迁移 / bù dàng qiān yí / bat1dong3cin1ji4"],
["不誠實","dishonesty / 不诚实 / bù chéng shí / bat1sing4sat6"],
["不誠實地獲益","dishonest gain / 不诚实地获益 / bù chéng shí dì huò yì / bat1sing4sat6dei6wok6jik1"],
["不認罪","plead not guilty / 不认罪 / bù rèn zuì / bat1jing6zeoi6"],
["不認罪的答辯","a plea of not guilty / 不认罪的答辩 / bù rèn zuì de dá biàn / bat1jing6zeoi6dik1daap3bin6"],
["不履行","failure / 不履行 / bù lǚ xíng / bat1lei5hang4"],
["不履行合約","repudiation of the contract / 不履行合约 / bù lǚ xíng hé yuē / bat1lei5hang4hap6joek3"],
["不確定權","possibility / 不确定权 / bù què dìng quán / bat1kok3ding6kyun4"],
["不遵守","failure to comply with / 不遵守 / bù zūn shǒu / bat1zeon1sau2"],
["不應訴的","non-appearing / 不应诉的 / bù yìng sù de / bat1jing3sou3dik1"],
["不營運公司","defunct companies / 不营运公司 / bù yíng yùn gōng sī / bat1jing4wan6gung1si1"],
["不屬法團的團體","unincorporated body / 不属法团的团体 / bù shǔ fǎ tuán de tuán tǐ / bat1suk6faat3tyun4dik1tyun4tai2"],
["世系","stock / 世系 / shì xì / sai3 hai6"],
["世界人權宣言","Universal Declaration of Human Rights / 世界人权宣言 / shì jiè rén quán xuān yán / sai3 gaai3 jan4 kyun4 syun1 jin4"],
["世界貿易組織協議","World Trade Organization Agreement / 世界贸易组织协议 / shì jiè mào yì zŭ zhī xié yì / sai3 gaai3 mau6 ji6 zou2 zik1 hip3 ji5"],
["並存令狀","concurrent writs / 并存令状 / bìng cún lìng zhuàng / bing6 cyun4 ling6 zong6"],
["中止","/abate/prorogue/ / 中止 / zhōng zhǐ / zung1zi2"],
["中止付款","suspend payment / 中止付款 / zhōng zhǐ fù kuǎn / zung1zi2fu6fun2"],
["中止實施","discontinue the operation / 中止实施 / zhōng zhǐ shí shī / zung1zi2sat6si1"],
["中止管有","discontinuance of possession / 中止管有 / zhōng zhǐ guǎn yǒu / zung1zi2gun2jau5"],
["中止檢控","nolle prosequi / 中止检控 / zhōng zhǐ jiǎn kòng / zung1zi2gim2hung3"],
["中央","Central Authorities / 中央 / zhōng yāng / zung1joeng1"],
["中央人民政府","Central People's Government / 中央人民政府 / zhōng yāng rén mín zhèng fǔ / zung1joeng1jan4man4zing3fu2"],
["中央人民政府委員會","Central People's Government Committee / 中央人民政府委员会 / zhōng yāng rén mín zhèng fǔ wěi yuán huì / zung1joeng1jan4man4zing3fu2wai2jun4wui2"],
["中央政府","central government / 中央政府 / zhōng yāng zhèng fǔ / zung1joeng1zing3fu2"],
["中央軍事委員會","Central Military Commission / 中央军事委员会 / zhōng yāng jūn shì wěi yuán huì / zung1joeng1gwan1si6wai2jun4wui2"],
["中央軍事委員會主席","Chairman of the Central Military Commission / 中央军事委员会主席 / zhōng yāng jūn shì wěi yuán huì zhǔ xí / zung1joeng1gwan1si6wai2jun4wui2zyu2zik6"],
["中央銀行","central bank / 中央银行 / zhōng yāng yín háng / zung1joeng1ngan4hong4"],
["中國人民政治協商會議","Chinese People's Political Consultative Conference / 中国人民政治协商会议 / zhōng guó rén mín zhèng zhì xié shāng huì yì / zung1gwok3jan4man4zing3zi6hip3soeng1wui6ji5"],
["中國人民政治協商會議全國委員會","National Committee of the Chinese People's Political Consultative Conference / 中国人民政治协商会议全国委员会 /  zhōng guó rén mín zhèng zhì xié shāng huì yì quán guó wěi yuán huì  / zung1gwok3jan4man4zing3zi6hip3soeng1wui6ji5cyun4gwok3wai2jun4wui2"],
["中國人民政治協商會議全國委員會主席","Chairman of the National Committee of the Chinese People's Political Consultative Conference / 中国人民政治协商会议全国委员会主席 /  zhōng guó rén mín zhèng zhì xié shāng huì yì quán guó wěi yuán huì zhǔ xí  / zung1gwok3jan4man4zing3zi6hip3soeng1wui6ji5cyun4gwok3wai2jun4wui2zyu2zik6"],
["中國公民","Chinese citizen/Chinese national/ / 中国公民 / zhōng guó gōng mín / zung1gwok3gung1man4"],
["中國法律與習俗","Chinese law and custom / 中国法律与习俗 / zhōng guó fǎ lǜ yǔ xí sú / zung1gwok3faat3leot6ju5zaap6zuk6"],
["中國國籍","Chinese nationality / 中国国籍 / zhōng guó guó jí / zung1gwok3gwok3zik6"],
["中國舊式婚姻","Chinese customary marriage / 中国旧式婚姻 / zhōng guó jiù shì hūn yīn / zung1gwok3gau6sik1fan1jan1"],
["中途停靠港","intermediate port / 中途停靠港 / zhōng tú tíng kào gǎng / zung1tou4ting4kaau3gong2"],
["中期付款","interim payment / 中期付款 / zhōng qī fù kuǎn / zung1kei4fu6fun2"],
["中期命令","interlocutory orders / 中期命令 / zhōng qī mìng lìng / zung1kei4ming6ling6"],
["中期報告","interim report / 中期报告 / zhōng qī bào gào / zung1kei4bou3gou3"],
["中期濟助","interim relief / 中期济助 / zhōng qī jì zhù / zung1kei4zai3zo6"],
["中期證明書","interim certificate / 中期证明书 / zhōng qī zhèng míng shū / zung1kei4zing3ming4syu1"],
["中華人民共和國","People's Republic of China / 中华人民共和国 / zhōng huá rén mín gòng hé guó / zung1waa4jan4man4gung6wo4gwok3"],
["中華人民共和國中央人民政府","Central People's Government of the People's Republic of China / 中华人民共和国中央人民政府 / zhōng huá rén mín gòng hé guó zhōng yāng rén mín zhèng fǔ / zung1waa4jan4man4gung6wo4gwok3zung1joeng1jan4man4zing3fu2"],
["中華人民共和國中央當局","Central Authorities of the People's Republic of China / 中华人民共和国中央当局 / zhōng huá rén mín gòng hé guó zhōng yāng dāng jú / zung1waa4jan4man4gung6wo4gwok3zung1joeng1dong1guk6"],
["中華人民共和國主席","President of the People's Republic of China / 中华人民共和国主席 / zhōng huá rén mín gòng hé guó zhǔ xí / zung1waa4jan4man4gung6wo4gwok3zyu2zik6"],
["中華人民共和國香港特別行政區","Hong Kong Special Administrative Region of the People's Republic of China / 中华人民共和国香港特别行政区 /  zhōng huá rén mín gòng hé guó xiāng gǎng tè bié xíng zhèng qū  / zung1waa4jan4man4gung6wo4gwok3hoeng1gong2dak6bit6hang4zing3keoi1"],
["中華人民共和國香港特別行政區基本法","Basic Law of the Hong Kong Special Administrative Region of the People's Republic of China / 中华人民共和国香港特别行政区基本法 /  zhōng huá rén mín gòng hé guó xiāng gǎng tè bié xíng zhèng qū jī běn fǎ  / zung1waa4jan4man4gung6wo4gwok3hoeng1gong2dak6bit6hang4zing3keoi1gei1bun2faat3"],
["中華人民共和國香港特別行政區駐軍法","Garrison Law of the Hong Kong Special Administrative Region of the People's Republic of China / 中华人民共和国香港特别行政区驻军法 /  zhōng huá rén mín gòng hé guó xiāng gǎng tè bié xíng zhèng qū zhù jūn fǎ  / zung1waa4jan4man4gung6wo4gwok3hoeng1gong2dak6bit6hang4zing3keoi1zyu3gwan1faat3"],
["中華人民共和國香港特別行政區籌備委員會","Preparatory Committee for the Hong Kong Special Administrative Region of the People's Republic of China / 中华人民共和国香港特别行政区筹备委员会 /  zhōng huá rén mín gòng hé guó xiāng gǎng tè bié xíng zhèng qū chóu bèi wěi yuán huì  / zung1waa4jan4man4gung6wo4gwok3hoeng1gong2dak6bit6hang4zing3keoi1cau4bei6wai2jun4wui2"],
["中華人民共和國國務院","State Council of the People's Republic of China / 中华人民共和国国务院 / zhōng huá rén mín gòng hé guó guó wù yuàn / zung1waa4jan4man4gung6wo4gwok3gwok3mou6jun2"],
["中間人","interposed person / 中间人 / zhōng jiān rén / zung1gaan1jan4"],
["中間收益","mesne profits / 中间收益 / zhōng jiān shōu yì / zung1gaan1sau1jik1"],
["中間業主","mesne landlord / 中间业主 / zhōng jiān yè zhǔ / zung1gaan1jip6zyu2"],
["中傷","vilification / 中伤 / zhòng shāng / zung1soeng1"],
["主犯","principal offender / 主犯 / zhŭ fàn / zyu2 faan6"],
["主任裁判官","Principal Magistrate / 主任裁判官 / zhŭ rèn cái pàn guān / zyu2 jam6 coi4 pun3 gun1"],
["主事人","principal / 主事人 / zhŭ shì rén / zyu2 si6 jan4"],
["主承建商","main contractor / 主承建商 / zhŭ chéng jiàn shāng / zyu2 sing4 gin3 soeng1"],
["主持","preside / 主持 / zhŭ chí / zyu2 ci4"],
["主持聆訊","preside at sittings / 主持聆讯 / zhŭ chí líng xùn / zyu2 ci4 ling4 seon3"],
["主要受益人","principal beneficiary / 主要受益人 / zhŭ yào shòu yì rén / zyu2 jiu3 sau6 jik1 jan4"],
["主要的居所","principal residence / 主要的居所 / zhŭ yào de jū suŏ / zyu2 jiu3 dik1 geoi1 so2"],
["主要的業務地點","chief place of business / 主要的业务地点 / zhŭ yào de yè wù dì diăn / zyu2 jiu3 dik1 jip6 mou6 dei6 dim2"],
["主要保證","principal security / 主要保证 / zhŭ yào băo zhèng / zyu2 jiu3 bou2 zing3"],
["主要債務人","principal debtor / 主要债务人 / zhŭ yào zhài wù rén / zyu2 jiu3 zaai3 mou6 jan4"],
["主要業務","principal business / 主要业务 / zhŭ yào yè wù / zyu2 jiu3 jip6 mou6"],
["主要業務地址","principal place of business  / 主要业务地址 / zhŭ yào yè wù dì zhĭ / zyu2 jiu3 jip6 mou6 dei6 zi2"],
["主要辦事處","principal office / 主要办事处 / zhŭ yào bàn shì chù / zyu2 jiu3 baan6 si6 cyu3"],
["主租客","principal tenant / 主租客 / zhŭ zū kè / zyu2 zou1 haak3"],
["主租賃","principal tenancy / 主租赁 / zhŭ zū lìn / zyu2 zou1 jam6"],
["主問","/examination in chief /examined in chief / / 主问 / zhŭ wèn / zyu2 man6"],
["主問證據","evidence in chief / 主问证据 / zhŭ wèn zhèng jù / zyu2 man6 zing3 geoi3"],
["主管司法機關","competent judicial authority / 主管司法机关 / zhŭ guăn sī fă jī guān / zyu2 gun2 si1 faat3 gei1 gwaan1"],
["主管船東","managing owner of the ship / 主管船东 / zhŭ guăn chuán dōng / zyu2 gun2 syun4 dung1"],
["主管當局","/authority/competent authority/ / 主管当局 / zhŭ guăn dāng jú / zyu2 gun2 dong1 guk6"],
["主審法官","trial judge / 主审法官 / zhŭ shĕn fă guān / zyu2 sam2 faat3 gun1"],
["主審裁判官","/adjudicating magistrate/presiding magistrate/ / 主审裁判官 / zhŭ shĕn cái pàn guān / zyu2 sam2 coi4 pun3 gun1"],
["主題","subject matter / 主题 / zhŭ tí / zyu2 tai4"],
["主權","/sovereign/sovereignty/ / 主权 / zhŭ quán / zyu2 kyun4"],
["主權國","sovereign powers / 主权国 / zhŭ quán guó / zyu2 kyun4 gwok3"],
["主權國政府","sovereign government / 主权国政府 / zhŭ quán guó zhèng fŭ / zyu2 kyun4 gwok3 zing3 fu2"],
["主權豁免","sovereign immunity / 主权豁免 / zhŭ quán huò miăn / zyu2 kyun4 kut3 min5"],
["主體條例","principal Ordinance / 主体条例 / zhŭ tĭ tiáo lì / zyu2 tai2 tiu4 lai6"],
["之前的所有權持有人","predecessor in title of / 之前的所有权持有人 / zhī qián de suǒ yǒu quán chí yǒu rén / zi1cin4dik1so2jau5kyun4ci4jau5jan4"],
["「乙種」換地權益書","Letter ‘B’ land exchange entitlements / 「乙种」换地权益书 / yǐ zhǒng huàn dì quán yì shū / jyut3zung2wun6dei6kyun4jik1syu1"],
["了結","/compound/liquidation/ / 了结 / liǎo jié / liu5git3"],
["了結申索","satisfies the claim / 了结申索 / liǎo jié shēn suǒ / liu5git3san1sok3"],
["了結法律程序","compound legal proceedings / 了结法律程序 / liǎo jié fǎ lǜ chéng xù / liu5git3faat3leot6cing4zeoi6"],
["了結訴訟因由","satisfaction of the cause of action / 了结诉讼因由 / liǎo jié sù sòng yīn yóu / liu5git3sou3zung6jan1jau4"],
["予以起訴","proceeded against / 予以起诉 / yǔ yǐ qǐ sù / ju6ji5hei2sou3"],
["互爭權利","interplead / 互争权利 / hù zhēng quán lì / wu6zang1kyun4lei6"],
["互爭權利訴訟","/interpleader/interpleader proceedings/ / 互争权利诉讼 / hù zhēng quán lì sù sòng / wu6zang1kyun4lei6sou3zung6"],
["互爭權利訴訟的法律程序","interpleader proceedings / 互争权利诉讼的法律程序 / hù zhēng quán lì sù sòng de fǎ lǜ chéng xù / wu6zang1kyun4lei6sou3zung6dik1faat3leot6cing4zeoi6"],
["互爭權利訴訟的爭論點","interpleader issue / 互争权利诉讼的争论点 / hù zhēng quán lì sù sòng de zhēng lùn diǎn / wu6zang1kyun4lei6sou3zung6dik1zang1leon6dim2"],
["互爭權利訴訟的傳票","interpleader summons / 互争权利诉讼的传票 / hù zhēng quán lì sù sòng de chuán piào / wu6zang1kyun4lei6sou3zung6dik1cyun4piu3"],
["互爭權利訴訟程序","interpleader proceedings / 互争权利诉讼程序 / hù zhēng quán lì sù sòng chéng xù / wu6zang1kyun4lei6sou3zung6cing4zeoi6"],
["互惠性安排","reciprocal arrangements / 互惠性安排 / hù huì xìng ān pái / wu6wai6sing3on1paai4/paai2"],
["互惠待遇","reciprocal treatment / 互惠待遇 / hù huì dài yù / wu6wai6doi6ju6"],
["互惠基金","mutual fund / 互惠基金 / hù huì jī jīn / wu6wai6gei1gam1"],
["互惠基金法團","mutual fund corporation / 互惠基金法团 / hù huì jī jīn fǎ tuán / wu6wai6gei1gam1faat3tyun4"],
["互選","elect from among themselves / 互选 / hù xuǎn / wu6syun2"],
["交付令狀","Writ of Delivery / 交付令状 / jiāo fù lìng zhuàng / gaau1 fu6 ling6 zong6"],
["交互協助","reciprocal assistance / 交互协助 / jiāo hù xié zhù / gaau1 wu6 hip3 zo6"],
["交互強制執行","reciprocal enforcement / 交互强制执行 / jiāo hù qiáng zhì zhí xíng / gaau1 wu6 koeng4 zai3 zap1 hang4"],
["交互執行國","reciprocating country / 交互执行国 / jiāo hù zhí xíng guó / gaau1 wu6 zap1 hang4 gwok3"],
["交付","/commitment/committal/deliver/delivery/ / 交付 / jiāo fù / gaau1 fu6"],
["交付扣押","committed to custody / 交付扣押 / jiāo fù kòu yā / gaau1 fu6 kau3 aat3"],
["交付判處","committed for sentence / 交付判处 / jiāo fù pàn chŭ / gaau1 fu6 pun3 cyu3"],
["交付審判","committed for trial / 交付审判 / jiāo fù shĕn pàn / gaau1 fu6 sam2 pun3"],
["交存","lodge / 交存 / jiāo cún / gaau1 cyun4"],
["交存通知書","notice of the lodgment / 交存通知书 / jiāo cún tōng zhī shū / gaau1 cyun4 tung1 zi1 syu1"],
["交易所","Exchange Company / 交易所 / jiāo yì suŏ / gaau1 ji6 so2"],
["交易限額","trading limit / 交易限额 / jiāo yì xiàn é / gaau1 ji6 haan6 ngaak6"],
["交易票據","instrument of exchange / 交易票据 / jiāo yì piào jù / gaau1 ji6 piu3 geoi3"],
["交相上訴","cross-appeal / 交相上诉 / jiāo xiāng shàng sù / gaau1 soeng1 soeng5 sou3"],
["交相申索","cross-claim / 交相申索 / jiāo xiāng shēn suŏ / gaau1 soeng1 san1 sok3"],
["交相判決","cross-judgments / 交相判决 / jiāo xiāng pàn jué / gaau1 soeng1 pun3 kyut3"],
["交相呈請","cross-petition / 交相呈请 / jiāo xiāng chéng qĭng / gaau1 soeng1 cing4 cing2"],
["交相對物訴訟","cross action in rem / 交相对物诉讼 / jiāo xiāng duì wù sù sòng / gaau1 soeng1 deoi3 mat6 sou3 zung6"],
["交相質詢","cross-interrogatories / 交相质询 / jiāo xiāng zhì xún / gaau1 soeng1 zat1 seon1"],
["交通督導員","traffic warden / 交通督导员 / jiāo tōng dū dăo yuán / gaau1 tung1 duk1 dou6 jyun4"],
["交換契據","deeds of exchange / 交换契据 / jiāo huàn qì jù / gaau1 wun6 kai3 geoi3"],
["交替申索","alternative claim / 交替申索 / jiāo tì shēn suŏ / gaau1 tai3 san1 sok3"],
["交替罪名","alternative count / 交替罪名 / jiāo tì zuì míng / gaau1 tai3 zeoi6 ming4"],
["人民","subjects / 人民 / rén mín / jan4man4"],
["人身","person / 人身 / rén shēn / jan4san1"],
["人身不得侵犯權","personal inviolability / 人身不得侵犯权 / rén shēn bù dé qīn fàn quán / jan4san1bat1dak1cam1faan6kyun4"],
["人身自由","personal freedom / 人身自由 / rén shēn zì yóu / jan4san1zi6jau4"],
["人身受到攻擊","attack on . . . person / 人身受到攻击 / rén shēn shòu dào gōng jī / jan4san1sau6dou3gung1gik1"],
["人身保護令","writ of habeas corpus / 人身保护令 / rén shēn bǎo hù lìng / jan4san1bou2wu6ling6"],
["人身保護令狀","writ of habeas corpus / 人身保护令状 / rén shēn bǎo hù lìng zhuàng / jan4san1bou2wu6ling6zong6"],
["人身傷害","personal injury / 人身伤害 / rén shēn shāng hài / jan4san1soeng1hoi6"],
["人身監護人","guardian of the person / 人身监护人 / rén shēn jiàn hù rén / jan4san1gaam1wu6jan4"],
["人事登記審裁處","Registration of Persons Tribunal / 人事登记审裁处 / rén shì dēng jì shěn cái chǔ / jan4si6dang1gei3sam2coi4cyu5"],
["人員","officer / 人员 / rén yuán / jan4jun4"],
["人道理由","humanitarian grounds / 人道理由 / rén dào lǐ yóu / jan4dou6lei5jau4"],
["人壽保險","life insurance / 人寿保险 / rén shòu bǎo xiǎn / jan4sau6bou2him2"],
["人壽保險單","life insurance policy / 人寿保险单 / rén shòu bǎo xiǎn dān / jan4sau6bou2him2daan1"],
["人種本源","ethnic origins / 人种本源 / rén zhǒng běn yuán / jan4zung2bun2jun4"],
["人質","hostage / 人质 / rén zhì / jan4zat1"],
["介入人","intervener / 介入人 / jiè rù rén / gaai3jap6jan4"],
["介入作為","intervening acts / 介入作为 / jiè rù zuò wéi / gaai3jap6zok3wai4/wai6"],
["介入訴訟","/intervene in an action/intervene in proceedings/ / 介入诉讼 / jiè rù sù sòng / gaai3jap6sou3zung6"],
["仍未了結","pending / 仍未了结 / réng wèi liǎo jié / jing4mei6liu5git3"],
["他罪成立的裁定","alternative convictions / 他罪成立的裁定 / tā zuì chéng lì de cái dìng / taa1 zeoi6 sing4 lap6 dik1 coi4 ding6"],
["付款人","payer / 付款人 / fù kuăn rén / fu6 fun2 jan4"],
["付款判決","judgment for money / 付款判决 / fù kuăn pàn jué / fu6 fun2 pun3 kyut3"],
["付款要求","demand / 付款要求 / fù kuăn yāo qiú / fu6 fun2 jiu3 kau4"],
["代","on behalf of / 代 / dài / doi6"],
["代位","subrogation / 代位 / dài wèi / doi6 wai2"],
["代位權利","right of subrogation / 代位权利 / dài wèi quán lì / doi6 wai2 kyun4 lei6"],
["代言人","advocate / 代言人 / dài yán rén / doi6 jin4 jan4"],
["代表","proxy / 代表 / dài biăo / doi6 biu2"],
["代表律師","counsel / 代表律师 / dài biăo lǜ shī / doi6 biu2 leot6 si1"],
["代理","deputy / 代理 / dài lĭ / doi6 lei5"],
["代理協議","agency agreements / 代理协议 / dài lĭ xié yì / doi6 lei5 hip3 ji5"],
["代理庭長","deputy of the President / 代理庭长 / dài lĭ tíng zhăng / doi6 lei5 ting4 coeng4"],
["代理商","factor / 代理商 / dài lĭ shāng / doi6 lei5 soeng1"],
["代理領事","pro-consul / 代理领事 / dài lĭ lĭng shì / doi6 lei5 ling5 si6"],
["代訟人","advocates / 代讼人 / dài sòng rén / doi6 zung6 jan4"],
["代通知金","/payment in lieu of notice/wages in lieu of notice / / 代通知金 / dài tōng zhī jīn / doi6 tung1 zi1 gam1"],
["代替假日","substituted holiday / 代替假日 / dài tì jià rì / doi6 tai3 gaa3 jat6"],
["代替監禁","in lieu of imprisonment / 代替监禁 / dài tì jiān jìn / doi6 tai3 gaam1 gam3"],
["代訴人","the proctor / 代诉人 / dài sù rén / doi6 sou3 jan4"],
["代價","consideration / 代价 / dài jià / doi6 gaa3"],
["代價收據","receipt for consideration / 代价收据 / dài jià shōu jù / doi6 gaa3 sau1 geoi3"],
["代辯人","attorney / 代辩人 / dài biàn rén / doi6 bin6 jan4"],
["令狀","/precept/warrant/writ/ / 令状 / lìng zhuàng / ling6 zong6"],
["令狀文稿","draft writ / 令状文稿 / lìng zhuàng wén găo / ling6 zong6 man4 gou2"],
["令狀正本","original writ / 令状正本 / lìng zhuàng zhèng bĕn / ling6 zong6 zing3 bun2"],
["仲裁","arbitration / 仲裁 / zhòng cái / zung6 coi4"],
["仲裁協議","arbitration agreement / 仲裁协议 / zhòng cái xié yì / zung6 coi4 hip3 ji5"],
["仲裁員","arbitrator / 仲裁员 / zhòng cái yuán / zung6 coi4 jyun4"],
["仲裁庭","/arbitration tribunal/arbitral tribunal/ / 仲裁庭 / zhòng cái tíng / zung6 coi4 ting4"],
["仲裁程序","/arbitral procedure/arbitration proceedings/ / 仲裁程序 / zhòng cái chéng xù / zung6 coi4 cing4 zeoi6"],
["仲裁裁決","arbitral award / 仲裁裁决 / zhòng cái cái jué / zung6 coi4 coi4 kyut3"],
["任期","/tenure of office/term of office/ / 任期 / rèn qī / jam6 kei4"],
["仿製火器","imitation firearm / 仿制火器 / făng zhì huŏ qì / fong2 zai3 fo2 hei3"],
["仿製品","imitation / 仿制品 / făng zhì pĭn / fong2 zai3 ban2"],
["企圖","attempt / 企图 / qĭ tú / kei5 tou4"],
["企圖妨礙司法公正","attempting to pervert the course of justice / 企图妨碍司法公正 / qĭ tú fáng ài sī fă gōng zhèng / kei5 tou4 fong4 ngoi6 si1 faat3 gung1 zing3"],
["企圖使人窒息","attempting to choke / 企图使人窒息 / qĭ tú shĭ rén zhì xī / kei5 tou4 sai2 jan4 zat6 sik1"],
["企圖強姦","attempted rape / 企图强奸 / qĭ tú qiáng jiān / kei5 tou4 koeng4 gaan1"],
["企圖謀殺","attempted murder / 企图谋杀 / qĭ tú móu shā / kei5 tou4 mau4 saat3"],
["休庭","the court adjourns / 休庭 / xiū tíng / jau1 ting4"],
["允許","assent / 允许 / yǔn xǔ / wan5heoi2"],
["允許書","assent / 允许书 / yǔn xǔ shū / wan5heoi2syu1"],
["允諾","promise / 允诺 / yǔn nuò / wan5nok6"],
["充公","/condemnation/confiscation/ / 充公 / chōng gōng / cung1 gung1"],
["充分拒認","sufficient traverse / 充分拒认 / chōng fèn jù rèn / cung1 fan1 keoi5 jing6"],
["充分送達","sufficient service / 充分送达 / chōng fèn sòng dá / cung1 fan1 sung3 daat6"],
["充分證據","sufficient evidence / 充分证据 / chōng fèn zhèng jù / cung1 fan1 zing3 geoi3"],
["充作","/passed off/pretend/purported compliance/ / 充作 / chōng zuò / cung1 zok3"],
["先決條件","condition precedent / 先决条件 / xiān jué tiáo jiàn / sin1 kyut3 tiu4 gin6"],
["先前法例","pre-existing legislation / 先前法例 / xiān qián fă lì / sin1 cin4 faat3 lai6"],
["入股金","premium / 入股金 / rù gǔ jīn / jap6gu2gam1"],
["入屋犯法","burglary / 入屋犯法 / rù wū fàn fǎ / jap6uk1faan6faat3"],
["入屋犯法罪","burglary / 入屋犯法罪 / rù wū fàn fǎ zuì / jap6uk1faan6faat3zeoi6"],
["入息稅","income tax / 入息税 / shōu rù shuì / jap6sik1seoi3"],
["入院令","hospital order / 入院令 / rù yuàn lìng / jap6jun6/jun2ling6"],
["入罪","incriminate / 入罪 / rù zuì / jap6zeoi6"],
["入境","land / 入境 / rù jìng / jap6ging2"],
["入境事務處羈留所","Immigration Department Detention Quarters / 入境事务处羁留所 / rù jìng shì wù chù jī liú suǒ / jap6ging2si6mou6cyu5gei1lau4so2"],
["入境事務審裁處","Immigration Tribunal / 入境事务审裁处 / rù jìng shì wù shěn cái chǔ / jap6ging2si6mou6sam2coi4cyu5"],
["入境者","immigrant / 入境者 / rù jìng zhě / jap6ging2ze2"],
["入境證","entry permit / 入境证 / rù jìng zhèng / jap6ging2zing3"],
["入學令","attendance order / 入学令 / rù xué lìng / jap6hok6ling6"],
["內地段","inland lot / 内地段 / nèi dì duàn / noi6dei6dyun6"],
["內庭","/chambers/in chambers/ / 内庭 / nèi tíng / noi6ting4"],
["內庭法官","judge in chambers / 内庭法官 / nèi tíng fǎ guān / noi6ting4faat3gun1"],
["內庭法律程序","proceedings in chambers / 内庭法律程序 / nèi tíng fǎ lǜ chéng xù / noi6ting4faat3leot6cing4zeoi6"],
["內庭處理","dispose of in chambers / 内庭处理 / nèi tíng chǔ lǐ / noi6ting4cyu5lei5"],
["內亂","/civil commotion/civil disturbance/ / 内乱 / nèi luàn / noi6lyun6"],
["內幕交易","insider dealing / 内幕交易 / nèi mù jiāo yì / noi6mok6gaau1jik6"],
["內幕交易者","insider dealer / 内幕交易者 / nèi mù jiāo yì zhě / noi6mok6gaau1jik6ze2"],
["內幕交易審裁處","Insider Dealing Tribunal / 内幕交易审裁处 / nèi mù jiāo yì shěn cái chǔ / noi6mok6gaau1jik6sam2coi4cyu5"],
["全日制教育","full-time education / 全日制教育 / quán rì zhì jiào yù / cyun4 jat6 zai3 gaau3 juk6"],
["全包價格","inclusive price / 全包价格 / quán bāo jià gé / cyun4 baau1 gaa3 gaak3"],
["全血親","/full blood/whole blood/ / 全血亲 / quán xuè qìng / cyun4 hyut3 can1"],
["全血親關係","relationship of the whole blood / 全血亲关系 / quán xuè qìng guān xì / cyun4 hyut3 can1 gwaan1 hai6"],
["全面聆訊","full hearing / 全面聆讯 / quán miàn líng xùn / cyun4 min6 ling4 seon3"],
["全面答辯及抗辯","full answer and defence / 全面答辩及抗辩 / quán miàn dá biàn jí kàng biàn / cyun4 min6 daap3 bin6 kap6 kong3 bin6"],
["全面審訊","full trial / 全面审讯 / quán miàn shĕn xùn / cyun4 min6 sam2 seon3"],
["全時間佔用","full-time occupation / 全时间占用 / quán shí jiān zhàn yòng / cyun4 si4 gaan1 zim3 jung6"],
["全部所有權","full ownership / 全部所有权 / quán bù suŏ yŏu quán / cyun4 bou6 so2 jau5 kyun4"],
["全資附屬公司","wholly-owned subsidiary / 全资附属公司 / quán zī fù shŭ gōng sī / cyun4 zi1 fu6 suk6 gung1 si1"],
["全資擁有","wholly owned / 全资拥有 / quán zī yōng yŏu / cyun4 zi1 jung2 jau5"],
["全職受僱","full time employment / 全职受雇 / quán zhí shòu gù / cyun4 zik1 sau6 gu3"],
["全額租金","rack rent / 全额租金 / quán é zū jīn / cyun4 ngaak6 zou1 gam1"],
["全權酌情決定","sole discretion / 全权酌情决定 / quán quán zhuó qíng jué dìng / cyun4 kyun4 zoek3 cing4 kyut3 ding6"],
["公允評論","fair comment / 公允评论 / gōng yǔn píng lùn / gung1wan5ping4leon6"],
["公司存在期限","duration of company / 公司存在期限 / gōng sī cún zài qī xiàn / gung1si1cyun4zoi6kei4haan6"],
["公司收購及合併守則","Code on Takeovers and Mergers / 公司收购及合并守则 / gōng sī shōu gòu jí hé bìng shǒu zé / gung1si1sau1kau3kap6hap6bing3sau2zak1"],
["公司註冊處處長","Registrar of Companies / 公司注册处处长 / gōng sī zhù cè chù chù cháng / gung1si1zyu3caak3cyu5cyu5zoeng2"],
["公司註冊證書","certificate of incorporation / 公司注册证书 / gōng sī zhù cè zhèng shū / gung1si1zyu3caak3zing3syu1"],
["公司檢查員","companies inspector / 公司检查员 / gōng sī jiǎn chá yuán / gung1si1gim2caa4jun4"],
["公佈","promulgate / 公布 / gōng bù / gung1bou3"],
["公佈其表決取向","announce his vote / 公布其表决取向 / gōng bù qí biǎo jué qǔ xiàng / gung1bou3kei4biu2kyut3ceoi2hoeng3"],
["公佈價格","published price / 公布价格 / gōng bù jià gé / gung1bou3gaa3gaak3"],
["公平","/equitable/just/ / 公平 / gōng píng / gung1ping4/peng4"],
["公正公平","just and equitable / 公正公平 / gōng zhèng gōng píng / gung1zing3gung1ping4"],
["公正因由","just cause / 公正因由 / gōng zhèng yīn yóu / gung1zing3jan1jau4"],
["公正的例外情況","just exception / 公正的例外情况 / gōng zhèng de lì wài qíng kuàng / gung1zing3dik1lai6ngoi6cing4fong3"],
["公正原則的例外情況","just exceptions / 公正原则的例外情况 / gōng zhèng yuán zé de lì wài qíng kuàng / gung1zing3jun4zak1dik1lai6ngoi6cing4fong3"],
["公民","/citizen/subjects/ / 公民 / gōng mín / gung1man4"],
["公民地位","citizenship / 公民地位 / gōng mín dì wèi / gung1man4dei6wai6"],
["公民身分","citizenship / 公民身分 / gōng mín shēn fèn / gung1man4san1fan6"],
["公民義務","civil obligations / 公民义务 / gōng mín yì wù / gung1man4ji6mou6"],
["公民權利和政治權利國際公約","International Covenant on Civil and Political Rights / 公民权利和政治权利国际公约 / gōng mín quán lì hé zhèng zhì quán lì guó jì gōng yuē / gung1man4kyun4lei6wo4zing3zi6kyun4lei6gwok3zai3gung1joek3"],
["公共文件","public documents / 公共文件 / gōng gòng wén jiàn / gung1gung6man4gin6"],
["公共主管當局","/competent public authorities/public authority/ / 公共主管当局 / gōng gòng zhǔ guǎn dāng jú / gung1gung6zyu2gun2dong1guk6"],
["公共收入","public revenue / 公共收入 / gōng gòng shōu rù / gung1gung6sau1jap6"],
["公共利益基金","common-good fund / 公共利益基金 / gōng gòng lì yì jī jīn / gung1gung6lei6jik1gei1gam1"],
["公共或地方當局","public or local authority / 公共或地方当局 / gōng gòng huò dì fang dāng jú / gung1gung6waak6dei6fong1dong13guk6"],
["公共法定法團","public statutory corporation / 公共法定法团 / gōng gòng fǎ dìng fǎ tuán / gung1gung6faat3ding6faat3tyun4"],
["公共政策","public policy / 公共政策 / gōng gòng zhèng cè / gung1gung6zing3caak3"],
["公共秩序","public order / 公共秩序 / gōng gòng zhì xù / gung1gung6dit6zeoi6"],
["公共無線電通訊服務牌照","public radiocommunication service licence / 公共无线电通讯服务牌照 / gōng gòng wú xiàn diàn tōng xùn fú wù pái zhào / gung1gung6mou4sin3din6tung1seon3fuk6mou6paai4ziu3"],
["公共機構","/public authority/public body/ / 公共机构 / gōng gòng jī gòu / gung1gung6gei1kau3"],
["公共機構僱員","servant of a public body / 公共机构雇员 / gōng gòng jī gòu gù yuán / gung1gung6gei1kau3gu3jun4"],
["公共機關","public department / 公共机关 / gōng gòng jī guān / gung1gung6gei1gwaan1"],
["公共權力機關","public authorities / 公共权力机关 / gōng gòng quán lì jī guān / gung1gung6kyun4lik6gei1gwaan1"],
["公印","Public Seal / 公印 / gōng yìn / gung1jan3"],
["公告","notice / 公告 / gōng gào / gung1gou3"],
["公事上的作為","official acts / 公事上的作为 / gōng shì shàng de zuò wéi / gung1si6soeng6dik1zok3wai4"],
["公使","envoy / 公使 / gōng shǐ / gung1si2"],
["公帑","/public funds/public moneys/ / 公帑 / gōng tǎng / gung1tong2"],
["公契","deed of mutual covenant / 公契 / gōng qì / gung1kai3"],
["公約","convention / 公约 / gōng yuē / gung1joek3"],
["公約的締約成員","party to Convention / 公约的缔约成员 / gōng yuē de dì yuē chéng yuán / gung1joek3dik1dai3joek3sing4jun4"],
["公約國","/Convention country/Convention State/ / 公约国 / gōng yuē guó / gung1joek3gwok3"],
["公約船","Convention ship / 公约船 / gōng yuē chuán / gung1joek3syun4"],
["公約裁決","Convention award / 公约裁决 / gōng yuē cái jué / gung1joek3coi4kyut3"],
["公約證明書","Convention certificates / 公约证明书 / gōng yuē zhèng míng shū / gung1joek3zing3ming4syu1"],
["公海","high seas / 公海 / gōng hǎi / gung1hoi2"],
["公務人員","/public official/public servant/ / 公务人员 / gōng wù rén yuán / gung1mou6jan4jun4"],
["公務人員體系","public service / 公务人员体系 / gōng wù rén yuán tǐ xì / gung1mou6jan4jun4tai2hai6"],
["公務員","public servant / 公务员 / gōng wù yuán / gung1mou6jun4"],
["公務員事務規例","Civil Service Regulations / 公务员事务规例 / gōng wù yuán shì wù guī lì / gung1mou6jun4si6mou6kwai1lai6"],
["公務員敘用委員會","Public Service Commission / 公务员叙用委员会 / gōng wù yuán 敍 yòng wěi yuán huì / gung1mou6jun4zeoi6jung6wai2jun4wui2"],
["公眾","public / 公众 / gōng zhòng / gung1zung3"],
["公眾人士","public / 公众人士 / gōng zhòng rén shì / gung1zung3jan4si6"],
["公眾公司","public companies / 公众公司 / gōng zhòng gōng sī / gung1zung3gung1si1"],
["公眾安寧","public peace / 公众安宁 / gōng zhòng ān níng / gung1zung3on1ning4"],
["公眾利益","/public advantage/public benefit/public interest/ / 公众利益 / gōng zhòng lì yì / gung1zung3lei6jik1"],
["公眾取用","public access / 公众取用 / gōng zhòng qǔ yòng / gung1zung3ceoi2jung6"],
["公眾保稅倉","public bonded warehouse / 公众保税仓 / gōng zhòng bǎo shuì cāng / gung1zung3bou2seoi3cong1"],
["公眾查閱期","public inspection period / 公众查阅期 / gōng zhòng chá yuè qī / gung1zung3caa4jyut6kei4"],
["公眾海旁","public water-front / 公众海旁 / gōng zhòng hǎi páng / gung1zung3hoi2pong4"],
["公眾假日","/general holiday/public holiday/ / 公众假日 / gōng zhòng jià rì / gung1zung3gaa3jat6"],
["公眾假期","/general holiday/public holiday/ / 公众假期 / gōng zhòng jià qī / gung1zung3gaa3kei4"],
["公眾條例","public Ordinance / 公众条例 / gōng zhòng tiáo lì / gung1zung3tiu4lai6"],
["公眾集結場所","place of public assembly / 公众集结场所 / gōng zhòng jí jié chǎng suǒ / gung1zung3zaap6git3coeng4so2"],
["公眾騷亂","public disturbance / 公众骚乱 / gōng zhòng sāo luàn / gung1zung3sou1lyun6"],
["公訴","indictment / 公诉 / gōng sù / gung1sou3"],
["公訴法律程序","proceedings on indictment / 公诉法律程序 / gōng sù fǎ lǜ chéng xù / gung1sou3faat3leot6cing4zeoi6"],
["公訴書","/bill of indictment/indictment/ / 公诉书 / gōng sù shū / gung1sou3syu1"],
["公訴書擬稿","bill of indictment / 公诉书拟稿 / gōng sù shū nǐ gǎo / gung1sou3syu1ji5gou2"],
["公訴提控","arraigned / 公诉提控 / gōng sù tí kòng / gung1sou3tai4hung3"],
["公訴程序","indictment / 公诉程序 / gōng sù chéng xù / gung1sou3cing4zeoi6"],
["公訴罪行","indictable offence / 公诉罪行 / gōng sù zuì xíng / gung1sou3zeoi6haang4"],
["公開投標","public tender / 公开投标 / gōng kāi tóu biāo / gung1hoi1tau4biu1"],
["公開拍賣","public auction / 公开拍卖 / gōng kāi pāi mài / gung1hoi1paak3maai6"],
["公開法律程序","proceedings in public / 公开法律程序 / gōng kāi fǎ lǜ chéng xù / gung1hoi1faat3leot6cing4zeoi6"],
["公開法庭","open court / 公开法庭 / gōng kāi fǎ tíng / gung1hoi1faat3ting4"],
["公開研訊程序","proceedings in public / 公开研讯程序 / gōng kāi yán xùn chéng xù / gung1hoi1jin4seon3cing4zeoi6"],
["公開訊問","public examination / 公开讯问 / gōng kāi xùn wèn / gung1hoi1seon3man6"],
["公開聆訊","/heard in open court/public hearing/ / 公开聆讯 / gōng kāi líng xùn / gung1hoi1ling4seon3"],
["公開聆訊方式","open court / 公开聆讯方式 / gōng kāi líng xùn fāng shì / gung1hoi1ling4seon3fong1sik1"],
["公開議事程序","proceedings in public / 公开议事程序 / gōng kāi yì shì chéng xù / gung1hoi1ji5si6cing4zeoi6"],
["公認配偶","reputed spouse / 公认配偶 / gōng rèn pèi 'ǒu / gung1jing6pui3ngau5"],
["公敵","public enemy / 公敌 / gōng dí / gung1dik6"],
["公敵行為","act of public-enemies / 公敌行为 / gōng dí xíng wéi / gung1dik6hang4wai4"],
["公曆月","calendar month / 公历月 / gōng lì yuè / gung1lik6jyut6"],
["公曆年","calendar year / 公历年 / gōng lì nián / gung1lik6nin4"],
["公積金","provident fund / 公积金 / gōng jī jīn / gung1zik1gam1"],
["公營單位","public sector entity / 公营单位 / gōng yíng dān wèi / gung1jing4daan1wai2"],
["公斷","reference / 公断 / gōng duàn / gung1dyun6"],
["公斷人","umpire / 公断人 / gōng duàn rén / gung1dyun6jan4"],
["公職","/public office/public service/ / 公职 / gōng zhí / gung1zik1"],
["公職人員","/public officer/public servant/ / 公职人员 / gōng zhí rén yuán / gung1zik1jan4jun4"],
["公職人員法團","incorporated public officer / 公职人员法团 / gōng zhí rén yuán fǎ tuán / gung1zik1jan4jun4faat3tyun4"],
["公職服務","public service / 公职服务 / gōng zhí fú wù / gung1zik1fuk6mou6"],
["公職檢控官","public prosecutor / 公职检控官 / gōng zhí jiǎn kòng guān / gung1zik1gim2hung3gun1"],
["公證人","notary public / 公证人 / gōng zhèng rén / gung1zing3jan4"],
["公證人註冊紀錄冊","register of notaries public / 公证人注册纪录册 / gōng zhèng rén zhù cè jì lù cè / gung1zing3jan4zyu3caak3gei2luk6caak3"],
["公證行為","/notarial acts/notarial act/ / 公证行为 / gōng zhèng xíng wéi / gung1zing3hang4wai4"],
["公證承付","/act of honour/notarial act of honour/ / 公证承付 / gōng zhèng chéng fù / gung1zing3sing4fu6"],
["公證特權","notarial faculty / 公证特权 / gōng zhèng tè quán / gung1zing3dak6kyun4"],
["公證開支","notarial expenses / 公证开支 / gōng zhèng kāi zhī / gung1zing3hoi1zi1"],
["公攤辦法","pooling arrangements / 公摊办法 / gōng tān bàn fǎ / gung1taan1baan6faat3"],
["共分疏忽","contributory negligence / 共分疏忽 / gòng fēn shū hu / gung6 fan1 so1 fat1"],
["共犯","joint offenders / 共犯 / gòng fàn / gung6 faan6"],
["共同立約人","co-contractor / 共同立约人 / gòng tóng lì yuē rén / gung6 tung4 lap6 joek3 jan4"],
["共同合約","joint contract / 共同合约 / gòng tóng hé yuē / gung6 tung4 hap6 joek3"],
["共同合夥","co-partnership / 共同合伙 / gòng tóng hé huŏ / gung6 tung4 hap6 fo2"],
["共同合夥人","co-partners / 共同合伙人 / gòng tóng hé huŏ rén / gung6 tung4 hap6 fo2 jan4"],
["共同有責","jointly liable / 共同有责 / gòng tóng yŏu zé / gung6 tung4 jau5 zaak3"],
["共同利益","mutual interests / 共同利益 / gòng tóng lì yì / gung6 tung4 lei6 jik1"],
["共同協議","common agreement / 共同协议 / gòng tóng xié yì / gung6 tung4 hip3 ji5"],
["共同受託人","co-trustee / 共同受托人 / gòng tóng shòu tuō rén / gung6 tung4 sau6 tok3 jan4"],
["共同受權人","joint attorneys / 共同受权人 / gòng tóng shòu quán rén / gung6 tung4 sau6 kyun4 jan4"],
["共同所有人","joint proprietors / 共同所有人 / gòng tóng suŏ yŏu rén / gung6 tung4 so2 jau5 jan4"],
["共同承租人","co-lessee / 共同承租人 / gòng tóng chéng zū rén / gung6 tung4 sing4 zou1 jan4"],
["共同東主","co-owners / 共同东主 / gòng tóng dōng zhŭ / gung6 tung4 dung1 zyu2"],
["共同海損","general average / 共同海损 / gòng tóng hăi sŭn / gung6 tung4 hoi2 syun2"],
["共同疏忽","contributory negligence / 共同疏忽 / gòng tóng shū hu / gung6 tung4 so1 fat1"],
["共同答辯人","co-respondent / 共同答辩人 / gòng tóng dá biàn rén / gung6 tung4 daap3 bin6 jan4"],
["共同債務人","/co-debtor/joint debtors/ / 共同债务人 / gòng tóng zhài wù rén / gung6 tung4 zaai3 mou6 jan4"],
["共同債項","joint debts / 共同债项 / gòng tóng zhài xiàng / gung6 tung4 zaai3 hong6"],
["共同監護人","joint guardians / 共同监护人 / gòng tóng jiān hù rén / gung6 tung4 gaam1 wu6 jan4"],
["共同擔保人","co-surety / 共同担保人 / gòng tóng dān băo rén / gung6 tung4 daam1 bou2 jan4"],
["共同繼承人","parceners / 共同继承人 / gòng tóng jì chéng rén / gung6 tung4 gai3 sing4 jan4"],
["共同權力","joint power / 共同权力 / gòng tóng quán lì / gung6 tung4 kyun4 lik6"],
["共謀","collusion / 共谋 / gòng móu / gung6 mau4"],
["再度定罪","subsequent conviction / 再度定罪 / zài dù dìng zuì / zoi3 dou6 ding6 zeoi6"],
["再度開庭","the court reassembles / 再度开庭 / zài dù kāi tíng / zoi3 dou6 hoi1 ting4"],
["再度傳召證人","recall witnesses / 再度传召证人 / zài dù chuán zhāo zhèng rén / zoi3 dou6 cyun4 ziu6 zing3 jan4"],
["出口授權書","export authorization / 出口授权书 / chū kŏu shòu quán shū / ceot1 hau2 sau6 kyun4 syu1"],
["出口許可證","export licence / 出口许可证 / chū kŏu xŭ kĕ zhèng / ceot1 hau2 heoi2 ho2 zing3"],
["出口證明書","export certificate / 出口证明书 / chū kŏu zhèng míng shū / ceot1 hau2 zing3 ming4 syu1"],
["出生冊","births register / 出生册 / chū shēng cè / ceot1 saang1 caak3"],
["出生登記證明書","Certificate of Registration of Birth / 出生登记证明书 / chū shēng dēng jì zhèng míng shū / ceot1 saang1 dang1 gei3 zing3 ming4 syu1"],
["出示","produce / 出示 / chū shì / ceot1 si6"],
["出於自衛","in his own defence / 出于自卫 / chū yú zì wèi / ceot1 jyu1 zi6 wai6"],
["出席聆訊","present at a hearing / 出席聆讯 / chū xí líng xùn / ceot1 zik6 ling4 seon3"],
["出庭","/appear/appearance/ / 出庭 / chū tíng / ceot1 ting4"],
["出庭代訟","advocacy / 出庭代讼 / chū tíng dài sòng / ceot1 ting4 doi6 zung6"],
["出庭作證人","to attend as a witness / 出庭作证人 / chū tíng zuò zhèng rén / ceot1 ting4 zok3 zing3 jan4"],
["出庭爭辯","argue before the court / 出庭争辩 / chū tíng zhēng biàn / ceot1 ting4 zang1 bin6"],
["出庭發言權","right of audience / 出庭发言权 / chū tíng fā yán quán / ceot1 ting4 faat3 jin4 kyun4"],
["出租","lease / 出租 / chū zū / ceot1 zou1"],
["出租人","lessor / 出租人 / chū zū rén / ceot1 zou1 jan4"],
["出售","sell / 出售 / chū shòu / ceot1 sau6"],
["出售所得收益","proceeds of sale / 出售所得收益 / chū shòu suŏ dé shōu yì / ceot1 sau6 so2 dak1 sau1 jik1"],
["出售證明書","certificate of sale / 出售证明书 / chū shòu zhèng míng shū / ceot1 sau6 zing3 ming4 syu1"],
["出獄","discharge from prison / 出狱 / chū yù / ceot1 juk6"],
["出讓","assign / 出让 / chū ràng / ceot1 joeng6"],
["出讓人","transferor / 出让人 / chū ràng rén / ceot1 joeng6 jan4"],
["分包合約","subcontract / 分包合约 / fēn bāo hé yuē / fan1baau1hap6joek3"],
["分包銷","sub-underwriting / 分包销 / fēn bāo xiāo / fan1baau1siu1"],
["分包銷合約","subunderwriting contract / 分包销合约 / fēn bāo xiāo hé yuē / fan1baau1siu1hap6joek3"],
["分行登記證","branch registration certificate / 分行登记证 / fēn háng dēng jì zhèng / fan1hong4dang1gei3zing3"],
["分居","separation / 分居 / fēn jū / fan1geoi1"],
["分居契據","deed of separation / 分居契据 / fēn jū qì jù / fan1geoi1kai3geoi3"],
["分居配偶","separated spouse / 分居配偶 / fēn jū pèi 'ǒu / fan1geoi1pui3ngau5"],
["分契","sub-deed / 分契 / fēn qì / fan1kai3"],
["分段","section / 分段 / fēn duàn / fan1dyun6"],
["分租","/sub-lease/sub-letting/sublet/underlease/underlet/ / 分租 / fēn zū / fan1zou1"],
["分租人","under-lessor / 分租人 / fēn zū rén / fan1zou1jan4"],
["分租承租人","sub-lessee / 分租承租人 / fēn zū chéng zū rén / fan1zou1sing4zou1jan4"],
["分租契","sub-lease / 分租契 / fēn zū qì / fan1zou1kai3"],
["分租契承租人","sub-lessee / 分租契承租人 / fēn zū qì chéng zū rén / fan1zou1kai3sing4zou1jan4"],
["分租客","sub-tenant / 分租客 / fēn zū kè / fan1zou1haak3"],
["分租約","underlease / 分租约 / fēn zū yuē / fan1zou1joek3"],
["分租租契","/sub-lease/under-lease/ / 分租租契 / fēn zū zū qì / fan1zou1zou1kai3"],
["分租租契協議","agreement for an under-lease / 分租租契协议 / fēn zū zū qì xié yì / fan1zou1zou1kai3hip3ji5"],
["分租租賃","sub-tenancy / 分租租赁 / fēn zū zū lìn / fan1zou1zou1jam6"],
["分區土地註冊處","District Land Registry / 分区土地注册处 / fēn qū tǔ dì zhù cè chù / fan1keoi1tou2dei6zyu3caak3cyu5"],
["分割","partitioned / 分割 / fēn gē / fan1got3"],
["分期","by instalments / 分期 / fēn qī / fan1kei4"],
["分期付款協議","hiring agreement / 分期付款协议 / fēn qī fù kuǎn xié yì / fan1kei4fu6fun2hip3ji5"],
["分期付款租購協議","hire purchase agreement / 分期付款租购协议 / fēn qī fù kuǎn zū gòu xié yì / fan1kei4fu6fun2zou1kau3hip3ji5"],
["分期執行的監禁刑期","consecutive sentences of imprisonment / 分期执行的监禁刑期 / fēn qī zhí xíng de jiān jìn xíng qī / fan1kei4zap1hang4dik1gaam1gam3jing4kei4"],
["分開居住","live apart / 分开居住 / fēn kāi jū zhù / fan1hoi1geoi1zyu6"],
["分開審訊","separate trial / 分开审讯 / fēn kāi shěn xùn / fan1hoi1sam2seon3"],
["分劃","partition / 分划 / fēn huà / fan1waak6"],
["分劃土地財產","partition of property in land / 分划土地财产 / fēn huà tǔ dì cái chǎn / fan1waak6tou2dei6coi4caan2"],
["分擔","contribution / 分担 / fēn dān / fan1daam1"],
["分擔人","contributory / 分担人 / fēn dān rén / fan1daam1jan4"],
["分擔提供","contribute / 分担提供 / fēn dān tí gōng / fan1daam1tai4gung1"],
["分擔款項","contribution / 分担款项 / fēn dān kuǎn xiàng / fan1daam1fun2hong6"],
["分擔費","contribution / 分担费 / fēn dān fèi / fan1daam1fai3"],
["分擔費用","contribution / 分担费用 / fēn dān fèi yòng / fan1daam1fai3jung6"],
["分擔開支令","Contribution Order / 分担开支令 / fēn dān kāi zhī lìng / fan1daam1hoi1zi1ling6"],
["分擔過失","contributory fault / 分担过失 / fēn dān guò shī / fan1daam1gwo3sat1"],
["分攤","/apportion/apportionment/ / 分摊 / fēn tān / fan1taan1"],
["分攤基準","basis of apportionment / 分摊基准 / fēn tān jī zhǔn / fan1taan1gei1zeon2"],
["分權共有","tenancy in common / 分权共有 / fēn quán gòng yǒu / fan1kyun4gung6jau5"],
["分權共有人","/co-owner/tenants in common/ / 分权共有人 / fēn quán gòng yǒu rén / fan1kyun4gung6jau5jan4"],
["分權共有財產","common property / 分权共有财产 / fēn quán gòng yǒu cái chǎn / fan1kyun4gung6jau5coi4caan2"],
["分權共有權","ownership in common / 分权共有权 / fēn quán gòng yǒu quán / fan1kyun4gung6jau5kyun4"],
["刑事上訴","criminal appeals / 刑事上诉 / xíng shì shàng sù / jing4 si6 soeng5 sou3"],
["刑事司法管轄權","criminal jurisdiction / 刑事司法管辖权 / xíng shì sī fă guăn xiá quán / jing4 si6 si1 faat3 gun2 hat6 kyun4"],
["刑事成文法則","penal enactments / 刑事成文法则 / xíng shì chéng wén fă zé / jing4 si6 sing4 man4 faat3 zak1"],
["刑事告發","criminal information / 刑事告发 / xíng shì gào fā / jing4 si6 gou3 faat3"],
["刑事法律責任","criminal liability / 刑事法律责任 / xíng shì fă lǜ zé rèn / jing4 si6 faat3 leot6 zaak3 jam6"],
["刑事恐嚇","criminal intimidation / 刑事恐吓 / xíng shì kŏng hè / jing4 si6 hung2 haak3"],
["刑事破產令","criminal bankruptcy order / 刑事破产令 / xíng shì pò chăn lìng / jing4 si6 po3 caan2 ling6"],
["刑事條文","criminal provisions / 刑事条文 / xíng shì tiáo wén / jing4 si6 tiu4 man4"],
["刑事訴訟","criminal litigation / 刑事诉讼 / xíng shì sù sòng / jing4 si6 sou3 zung6"],
["刑事疏忽","criminal negligence / 刑事疏忽 / xíng shì shū hu / jing4 si6 so1 fat1"],
["刑事毀壞","criminal damage / 刑事毁坏 / xíng shì huĭ huài / jing4 si6 wai2 waai6"],
["刑事罪行","criminal offence / 刑事罪行 / xíng shì zuì xíng / jing4 si6 zeoi6 hang4"],
["刑事審訊","criminal trial / 刑事审讯 / xíng shì shĕn xùn / jing4 si6 sam2 seon3"],
["刑事暴力","criminal violence / 刑事暴力 / xíng shì bào lì / jing4 si6 bou6 lik6"],
["刑事檢控","criminal prosecution / 刑事检控 / xíng shì jiăn kòng / jing4 si6 gim2 hung3"],
["刑事藐視罪","criminal contempt / 刑事藐视罪 / xíng shì miăo shì zuì / jing4 si6 miu5 si6 zeoi6"],
["刑期的縮減","remission of sentences / 刑期的缩减 / xíng qī de suō jiăn / jing4 kei4 dik1 suk1 gaam2"],
["刑罰","/penalty/sentence/ / 刑罚 / xíng fá / jing4 fat6"],
["功能組別","functional constituency / 功能组别 / gōng néng zŭ bié / gung1 nang4 zou2 bit6"],
["加租通知書","notice of increase / 加租通知书 / jiā zū tōng zhī shū / gaa1 zou1 tung1 zi1 syu1"],
["加簽","/countersigned/endorse/ / 加签 / jiā qiān / gaa1 cim1"],
["加權風險值","risk weighted exposure / 加权风险值 / jiā quán fēng xiăn zhí / gaa1 kyun4 fung1 him2 zik6"],
["包銷","underwrite / 包销 / bāo xiāo / baau1 siu1"],
["包銷合約","underwriting contract / 包销合约 / bāo xiāo hé yuē / baau1 siu1 hap6 joek3"],
["包銷協議","underwriting agreement / 包销协议 / bāo xiāo xié yì / baau1 siu1 hip3 ji5"],
["十足代價","full consideration / 十足代价 / shí zú dài jià / sap6zuk1doi6gaa3"],
["十足有值代價","full valuable consideration / 十足有值代价 / shí zú yǒu zhí dài jià / sap6zuk1jau5zik6doi6gaa3"],
["十足效力","full operation / 十足效力 / shí zú xiào lì / sap6zuk1haau6lik6"],
["十足訟費","full costs / 十足讼费 / shí zú sòng fèi / sap6zuk1zung6fai3"],
["十足彌償","complete indemnity / 十足弥偿 / shí zú mí cháng / sap6zuk1nei4soeng4"],
["半血親","halfblood / 半血亲 / bàn xuè qìng / bun3 hyut3 can1"],
["半血親關係","relationship of the half blood  / 半血亲关系 / bàn xuè qìng guān xì / bun3 hyut3 can1 gwaan1 hai6"],
["印花稅","stamp duty / 印花税 / yìn huā shuì / jan3 faa1 seoi3"],
["危及","jeopardise / 危及 / wēi jí / ngai4 kap6"],
["危害種族","genocide / 危害种族 / wēi hài zhŏng zú / ngai4 hoi6 zung2 zuk6"],
["危險品","dangerous goods / 危险品 / wēi xiăn pĭn / ngai4 him2 ban2"],
["危險藥物","dangerous drug / 危险药物 / wēi xiăn yào wù / ngai4 him2 joek6 mat6"],
["友好調解人","amiable compositeur / 友好调解人 / yǒu hǎo tiáo jiě rén / jau5hou2tiu4gaai2jan4"],
["反申索","counterclaim / 反申索 / fǎn shēn suǒ / faan2san1sok3"],
["反申索的抗辯書","defence to counterclaim / 反申索的抗辩书 / fǎn shēn suǒ de kàng biàn shū / faan2san1sok3dik1kong3bin6syu1"],
["反申索書","counterclaim / 反申索书 / fǎn shēn suǒ shū / faan2san1sok3syu1"],
["反向回購","reverse repos / 反向回购 / fǎn xiàng huí gòu / faan2hoeng3wui4kau3"],
["反指控","counter-charges / 反指控 / fǎn zhǐ kòng / faan2zi2hung3"],
["反指稱","counter allegations / 反指称 / fǎn zhǐ chēng / faan2zi2cing1"],
["反要求","cross demand / 反要求 / fǎn yāo qiú / faan2jiu3kau4"],
["反控告","counter-charges / 反控告 / fǎn kòng gào / faan2hung3gou3"],
["反通知書","counter-notice / 反通知书 / fǎn tōng zhī shū / faan2tung1zi1syu1"],
["反陳述","counter-statement / 反陈述 / fǎn chén shù / faan2can4seot6"],
["反訴","/counter-claim/cross-proceedings/ / 反诉 / fǎn sù / faan2sou3"],
["反對人","objector / 反对人 / fǎn duì rén / faan2deoi3jan4"],
["反對劫持人質國際公約","International Convention against the Taking of Hostages / 反对劫持人质国际公约 / fǎn duì jié chí rén zhì guó jì gōng yuē / faan2deoi3gip3ci4jan4zat1gwok3zai3gung1joek3"],
["反對者","objector / 反对者 / fǎn duì zhě / faan2deoi3ze2"],
["反對通知","notice of opposition / 反对通知 / fǎn duì tōng zhī / faan2deoi3tung1zi1"],
["反對通知書","/notice of objection/notice of opposition/ / 反对通知书 / fǎn duì tōng zhī shū / faan2deoi3tung1zi1syu1"],
["反對遺囑的一方","party opposing a will / 反对遗嘱的一方 / fǎn duì yí zhǔ de yī fāng / faan2deoi3wai4zuk1dik1jat1fong1"],
["反駁","/disprove/rebut/rebuttal/ / 反驳 / fǎn bó / faan2bok3"],
["反駁陳述","statement of objections / 反驳陈述 / fǎn bó chén shù / faan2bok3can4seot6"],
["反駁證據","rebutting evidence / 反驳证据 / fǎn bó zhèng jù / faan2bok3zing3geoi3"],
["反證","disproving / 反证 / fǎn zhèng / faan2zing3"],
["口述陳詞","oral submissions / 口述陈词 / kǒu shù chén cí / hau2seot6can4ci4"],
["口頭方式","viva voce / 口头方式 / kǒu tóu fāng shì / hau2tau4fong1sik1"],
["口頭的法律程序","oral proceedings / 口头的法律程序 / kǒu tóu de fǎ lǜ chéng xù / hau2tau4dik1faat3leot6cing4zeoi6"],
["口頭訊問","/examined viva voce/oral examination/ / 口头讯问 / kǒu tóu xùn wèn / hau2tau4seon3man6"],
["口頭問題","viva voce questions / 口头问题 / kǒu tóu wèn tí / hau2tau4man6tai4"],
["口頭陳述","oral statement / 口头陈述 / kǒu tóu chén shù / hau2tau4can4seot6"],
["口頭盤問","oral cross-examination / 口头盘问 / kǒu tóu pán wèn / hau2tau4pun4man6"],
["口頭覆問","re-examine viva voce / 口头覆问 / kǒu tóu fù wèn / hau2tau4fuk1man6"],
["口頭證供","oral testimony / 口头证供 / kǒu tóu zhèng gōng / hau2tau4zing3gung1"],
["口頭證據","oral evidence / 口头证据 / kǒu tóu zhèng jù / hau2tau4zing3geoi3"],
["另售權","right of re-sale / 另售权 / lìng shòu quán / ling6 sau6 kyun4"],
["召回令","recall order / 召回令 / zhào huí lìng / ziu6 wui4 ling6"],
["司法","/administration of justice/judicial/ / 司法 / sī fă / si1 faat3"],
["司法人員","judicial officer / 司法人员 / sī fă rén yuán / si1 faat3 jan4 jyun4"],
["司法不公","miscarriage of justice / 司法不公 / sī fă bù gōng / si1 faat3 bat1 gung1"],
["司法公正","justice / 司法公正 / sī fă gōng zhèng / si1 faat3 gung1 zing3"],
["司法文件","judicial documents / 司法文件 / sī fă wén jiàn / si1 faat3 man4 gin6"],
["司法判決","judicial decision / 司法判决 / sī fă pàn jué / si1 faat3 pun3 kyut3"],
["司法協助","judicial assistance / 司法协助 / sī fă xié zhù / si1 faat3 hip3 zo6"],
["司法受託人","judicial trustee / 司法受托人 / sī fă shòu tuō rén / si1 faat3 sau6 tok3 jan4"],
["司法科學","forensic science / 司法科学 / sī fă kē xué / si1 faat3 fo1 hok6"],
["司法書記","judicial clerk / 司法书记 / sī fă shū ji / si1 faat3 syu1 gei3"],
["司法財產保管人","judicial factor / 司法财产保管人 / sī fă cái chăn băo guăn rén / si1 faat3 coi4 caan2 bou2 gun2 jan4"],
["司法程序","/judicial proceedings/judicial process/ / 司法程序 / sī fă chéng xù / si1 faat3 cing4 zeoi6"],
["司法資格","judicial qualifications / 司法资格 / sī fă zī gé / si1 faat3 zi1 gaak3"],
["司法管轄區","jurisdiction / 司法管辖区 / sī fă guăn xiá qū / si1 faat3 gun2 hat6 keoi1"],
["司法認知","judicial notice / 司法认知 / sī fă rèn zhī / si1 faat3 jing6 zi1"],
["司法誓言","Judicial Oath / 司法誓言 / sī fă shì yán / si1 faat3 sai6 jin4"],
["司法調查","judicial investigations / 司法调查 / sī fă diào chá / si1 faat3 diu6 caa4"],
["司法職銜","judicial character / 司法职衔 / sī fă zhí xián / si1 faat3 zik1 haam4"],
["司法覆核","judicial review / 司法覆核 / sī fă fù hé / si1 faat3 fuk1 hat6"],
["司法體制","judicial institutions / 司法体制 / sī fă tĭ zhì / si1 faat3 tai2 zai3"],
["司理","manager / 司理 / sī lĭ / si1 lei5"],
["合法代表","legal representative / 合法代表 / hé fă dài biăo / hap6 faat3 doi6 biu2"],
["合乎公眾利益","desirable in the public interest / 合乎公众利益 / hé hū gōng zhòng lì yì / hap6 fu4 gung1 zung3 lei6 jik1"],
["合作市場","co-operative markets / 合作市场 / hé zuò shì chăng / hap6 zok3 si5 coeng4"],
["合作社","co-operative society / 合作社 / hé zuò shè / hap6 zok3 se5"],
["合併","/joinder/merger/ / 合并 / hé bìng / hap6 bing3"],
["合併訴訟","consolidated action / 合并诉讼 / hé bìng sù sòng / hap6 bing3 sou3 zung6"],
["合法分居","legal separations / 合法分居 / hé fă fēn jū / hap6 faat3 fan1 geoi1"],
["合法用途","lawful purpose / 合法用途 / hé fă yòng tú / hap6 faat3 jung6 tou4"],
["合法印章","lawful seal / 合法印章 / hé fă yìn zhāng / hap6 faat3 jan3 zoeng1"],
["合法行使","the lawful exercise / 合法行使 / hé fă xíng shĭ / hap6 faat3 hang4 sai2"],
["合法佔用","lawful occupation / 合法占用 / hé fă zhàn yòng / hap6 faat3 zim3 jung6"],
["合法拘留","lawful detention / 合法拘留 / hé fă jū liú / hap6 faat3 keoi1 lau4"],
["合法婚姻","lawful wedlock / 合法婚姻 / hé fă hūn yīn / hap6 faat3 fan1 jan1"],
["合法授權","lawful authority / 合法授权 / hé fă shòu quán / hap6 faat3 sau6 kyun4"],
["合法理由","lawful justification / 合法理由 / hé fă lĭ yóu / hap6 faat3 lei5 jau4"],
["合法期望","legitimate expectation / 合法期望 / hé fă qī wàng / hap6 faat3 kei4 mong6"],
["合法逮捕","lawful arrest / 合法逮捕 / hé fă dài bŭ / hap6 faat3 dai6 bou6"],
["合法管有","lawful possession / 合法管有 / hé fă guăn yŏu / hap6 faat3 gun2 jau5"],
["合法繼承人","legal heir / 合法继承人 / hé fă jì chéng rén / hap6 faat3 gai3 sing4 jan4"],
["合法辯解","lawful excuse / 合法辩解 / hé fă biàn jiĕ / hap6 faat3 bin6 gaai2"],
["合法羈押","lawful custody / 合法羁押 / hé fă jī yā / hap6 faat3 gei1 aat3"],
["合股公司","joint-stock company / 合股公司 / hé gŭ gōng sī / hap6 gu2 gung1 si1"],
["合約效力","contractual effect / 合约效力 / hé yuē xiào lì / hap6 joek3 haau6 lik6"],
["合約條文","contractual provision / 合约条文 / hé yuē tiáo wén / hap6 joek3 tiu4 man4"],
["合約條款","/contractual clauses/contractual terms/ / 合约条款 / hé yuē tiáo kuăn / hap6 joek3 tiu4 fun2"],
["合約船舶","contract ship / 合约船舶 / hé yuē chuán bó / hap6 joek3 syun4 baak3"],
["合約期","contractual period / 合约期 / hé yuē qī / hap6 joek3 kei4"],
["合約價","contract price / 合约价 / hé yuē jià / hap6 joek3 gaa3"],
["合格證明書","/certificate of compliance/certificate of competency/ / 合格证明书 / hé gé zhèng míng shū / hap6 gaak3 zing3 ming4 syu1"],
["合理可能性","reasonable probability / 合理可能性 / hé lĭ kĕ néng xìng / hap6 lei5 ho2 nang4 sing3"],
["合理努力","/reasonable diligence/endeavour/ / 合理努力 / hé lĭ nŭ lì / hap6 lei5 nou5 lik6"],
["合理武力","reasonable force / 合理武力 / hé lĭ wŭ lì / hap6 lei5 mou5 lik6"],
["合理推斷","reasonable inference / 合理推断 / hé lĭ tuī duàn / hap6 lei5 teoi1 tyun5"],
["合理期望","reasonable expectation / 合理期望 / hé lĭ qī wàng / hap6 lei5 kei4 mong6"],
["合理預見","reasonable foresight / 合理预见 / hé lĭ yù jiàn / hap6 lei5 jyu6 gin3"],
["合理疑點","reasonable doubt / 合理疑点 / hé lĭ yí diăn / hap6 lei5 ji4 dim2"],
["合理懷疑","reasonable suspicion / 合理怀疑 / hé lĭ huái yí / hap6 lei5 waai4 ji4"],
["合夥","partnership / 合伙 / hé huŏ / hap6 fo2"],
["合夥合約","/partnership contract/contract of copartnery/ / 合伙合约 / hé huŏ hé yuē / hap6 fo2 hap6 joek3"],
["合夥終止","termination of the partnership / 合伙终止 / hé huŏ zhōng zhĭ / hap6 fo2 zung1 zi2"],
["合夥業務","partnership business / 合伙业务 / hé huŏ yè wù / hap6 fo2 jip6 mou6"],
["合夥資產","partnership assets / 合伙资产 / hé huŏ zī chăn / hap6 fo2 zi1 caan2"],
["合議庭","Full Court / 合议庭 / hé yì tíng / hap6 ji5 ting4"],
["同居","cohabit / 同居 / tóng jū / tung4 geoi1"],
["同時執行","concurrent performance / 同时执行 / tóng shí zhí xíng / tung4 si4 zap1 hang4"],
["同樣罪行","like offence / 同样罪行 / tóng yàng zuì xíng / tung4 joeng6 zeoi6 hang4"],
["同謀","confederate / 同谋 / tóng móu / tung4 mau4"],
["同類個案","like cases / 同类个案 / tóng lèi gè àn / tung4 leoi6 go3 ngon3"],
["名義股本","nominal share capital / 名义股本 / míng yì gŭ bĕn / ming4 ji6 gu2 bun2"],
["名譽會員","honorary members / 名誉会员 / míng yù huì yuán / ming4 jyu6 wui2 jyun4"],
["名譽證據","evidence of a person's reputation / 名誉证据 / míng yù zhèng jù / ming4 jyu6 zing3 geoi3"],
["呈請令狀","petition warrant / 呈请令状 / chéng qĭng lìng zhuàng / cing4 cing2 ling6 zong6"],
["囚犯","prisoner / 囚犯 / qiú fàn / cau4 faan6"],
["囚禁","confinement / 囚禁 / qiú jìn / cau4 gam3"],
["囚禁紀律","custodial discipline / 囚禁纪律 / qiú jìn jì lǜ / cau4 gam3 gei2 leot6"],
["回傭","rebate / 回佣 / huí yòng / wui4 jung4"],
["回報日","return day / 回报日 / huí bào rì / wui4 bou3 jat6"],
["回港證","re-entry permi / 回港证 / huí găng zhèng / wui4 gong2 zing3"],
["回答質詢","answer interrogatories / 回答质询 / huí dá zhì xún / wui4 daap3 zat1 seon1"],
["回歸","reunification / 回归 / huí guī / wui4 gwai1"],
["土地","land / 土地 / tǔ dì / tou2dei6"],
["土地及其他財產","real and assumed property / 土地及其他财产 / tǔ dì jí qí tā cái chǎn / tou2dei6kap6kei4taa1coi4caan2"],
["土地交換權利","land exchange entitlement / 土地交换权利 / tǔ dì jiāo huàn quán lì / tou2dei6gaau1wun6kyun4lei6"],
["土地估價","land valuation / 土地估价 / tǔ dì gū jià / tou2dei6gu2gaa3"],
["土地委員會","Land Commission / 土地委员会 / tǔ dì wěi yuán huì / tou2dei6wai2jun4wui2"],
["土地契約","leases of land / 土地契约 / tǔ dì qì yuē / tou2dei6kai3joek3"],
["土地按揭","mortgage on land / 土地按揭 / tǔ dì dǐ yā / tou2dei6on3kit3"],
["土地租賃為不定期","land . . . held by . . . at will / 土地租赁为不定期 / tǔ dì zū lìn wéi bù dìng qī / tou2dei6zou1jam6wai4bat1ding6kei4"],
["土地財產","real property / 土地财产 / tǔ dì cái chǎn / tou2dei6coi4caan2"],
["土地通行權","wayleave / 土地通行权 / tǔ dì tōng xíng quán / tou2dei6tung1hang4kyun4"],
["土地發展公司","Land Development Corporation / 土地发展公司 / tǔ dì fā zhǎn gōng sī / tou2dei6faat3zin2gung1si1"],
["土地註冊","land registration / 土地注册 / tǔ dì zhù cè / tou2dei6zyu3caak3"],
["土地註冊處","Land Registry / 土地注册处 / tǔ dì zhù cè chù / tou2dei6zyu3caak3cyu5"],
["土地註冊處處長","Land Registrar / 土地注册处处长 / tǔ dì zhù cè chù chù cháng / tou2dei6zyu3caak3cyu5cyu5zoeng2"],
["土地註冊處註冊紀錄冊","Land Registry register / 土地注册处注册纪录册 / tǔ dì zhù cè chù zhù cè jì lù cè / tou2dei6zyu3caak3cyu5zyu3caak3gei2luk6caak3"],
["土地訴訟","real action / 土地诉讼 / tǔ dì sù sòng / tou2dei6sou3zung6"],
["土地審裁處","Lands Tribunal / 土地审裁处 / tǔ dì shěn cái chǔ / tou2dei6sam2coi4cyu5"],
["土地審裁處法官","Presiding Officer, Lands Tribunal / 土地审裁处法官 / tǔ dì shěn cái chǔ fǎ guān / tou2dei6sam2coi4cyu5faat3gun1"],
["土地審裁處庭長","President, Lands Tribunal / 土地审裁处庭长 / tǔ dì shěn cái chǔ tíng zhǎng / tou2dei6sam2coi4cyu5ting4zoeng2"],
["土地徵用","land acquisition / 土地征用 / tǔ dì zhēng yòng / tou2dei6zing1jung6"],
["土地遺贈繼承人","devisee / 土地遗赠继承人 / tǔ dì yí zèng jì chéng rén / tou2dei6wai4zang6gai3sing4jan4"],
["土地權益","interests in land / 土地权益 / tǔ dì quán yì / tou2dei6kyun4jik1"],
["地方選區","geographical constituency / 地方选区 / dì fang xuăn qū / dei6 fong1 syun2 keoi1"],
["地役權","easement / 地役权 / dì yì quán / dei6 jik6 kyun4"],
["地段","lot / 地段 / dì duàn / dei6 dyun6"],
["地段編號","lot number / 地段编号 / dì duàn biān hào / dei6 dyun6 pin1 hou6"],
["地區","territory / 地区 / dì qū / dei6 keoi1"],
["地區限制","geographical limitation / 地区限制 / dì qū xiàn zhì / dei6 keoi1 haan6 zai3"],
["地域範圍","territorial limits / 地域范围 / dì yù fàn wéi / dei6 wik6 faan6 wai4"],
["外交代表","diplomatic agent / 外交代表 / wài jiāo dài biăo / ngoi6 gaau1 doi6 biu2"],
["外交人員","diplomatic agent / 外交人员 / wài jiāo rén yuán / ngoi6 gaau1 jan4 jyun4"],
["外交豁免權","diplomatic immunities / 外交豁免权 / wài jiāo huò miăn quán / ngoi6 gaau1 kut3 min5 kyun4"],
["外地司法管轄區","foreign jurisdiction / 外地司法管辖区 / wài dì sī fă guăn xiá qū / ngoi6 dei6 si1 faat3 gun2 hat6 keoi1"],
["外地判決","foreign judgments / 外地判决 / wài dì pàn jué / ngoi6 dei6 pun3 kyut3"],
["外地沒收令","external confiscation order / 外地没收令 / wài dì mò shōu lìng / ngoi6 dei6 mut6 sau1 ling6"],
["外地承付票","foreign note / 外地承付票 / wài dì chéng fù piào / ngoi6 dei6 sing4 fu6 piu3"],
["外地法律","foreign law / 外地法律 / wài dì fă lǜ / ngoi6 dei6 faat3 leot6"],
["外地稅款","foreign tax / 外地税款 / wài dì shuì kuăn / ngoi6 dei6 seoi3 fun2"],
["外地僱員津貼","expatriation pay / 外地雇员津贴 / wài dì gù yuán jīn tiē / ngoi6 dei6 gu3 jyun4 zeon1 tip3"],
["外匯","foreign exchange / 外汇 / wài huì / ngoi6 wui6"],
["外匯基金","Exchange Fund / 外汇基金 / wài huì jī jīn / ngoi6 wui6 gei1 gam1"],
["外幣","foreign currency / 外币 / wài bì / ngoi6 bai6"],
["多次入境證","entry permit for multiple entries / 多次入境证 / duō cì rù jìng zhèng / do1 ci3 jap6 ging2 zing3"],
["多次通用回港證","multiple re-entry permit / 多次通用回港证 / duō cì tōng yòng huí găng zhèng / do1 ci3 tung1 jung6 wui4 gong2 zing3"],
["多界別學科業務","multidisciplinary practice / 多界别学科业务 / duō jiè bié xué kē yè wù / do1 gaai3 bit6 hok6 fo1 jip6 mou6"],
["多配偶制","polygamous / 多配偶制 / duō pèi ŏu zhì / do1 pui3 ngau5 zai3"],
["多配偶制婚姻","/polygamous marriage/polygamy/ / 多配偶制婚姻 / duō pèi ŏu zhì hūn yīn / do1 pui3 ngau5 zai3 fan1 jan1"],
["多數票","plurality vote / 多数票 / duō shù piào / do1 sou3 piu3"],
["多數裁決","majority verdict / 多数裁决 / duō shù cái jué / do1 sou3 coi4 kyut3"],
["多邊公約","multilateral convention / 多边公约 / duō biān gōng yuē / do1 bin1 gung1 joek3"],
["大法官法庭、家事法庭及皇座法庭","Chancery, Family and Queen's Bench Divisions / 大法官法庭、家事法庭及皇座法庭 /  dà fǎ guān fǎ tíng 、 jiā shì fǎ tíng jí huáng zuò fǎ tíng  / daai6faat3gun1faat3ting4、gaa1si6faat3ting4kap6wong4zo6faat3ting4"],
["大股東","substantial shareholder / 大股东 / dà gǔ dōng / daai6gu2dung1"],
["大股東控權人","majority shareholder controller / 大股东控权人 / dà gǔ dōng kòng quán rén / daai6gu2dung1hung3kyun4jan4"],
["大律師","/barrister/barristers-at-law/counsel/ / 大律师 / dà lǜ shī / daai6leot6si1"],
["大律師公會","Hong Kong Bar Association / 大律师公会 / dà lǜ shī gōng huì / daai6leot6si1gung1wui62"],
["大律師名冊","panels of counsel / 大律师名册 / dà lǜ shī míng cè / daai6leot6si1ming4caak3"],
["大律師行業或律師行業","the practice of law / 大律师行业或律师行业 / dà lǜ shī háng yè huò lǜ shī háng yè / daai6leot6si1hong4jip6waak6leot6si1hong4jip6"],
["大律師見習職位","pupillage / 大律师见习职位 / dà lǜ shī jiàn xí zhí wèi / daai6leot6si1gin3zaap6zik1wai6"],
["大律師事務所","/barristers' chambers/chambers of counsel/ / 大律师事务所 / dà lǜ shī shì wù suǒ / daai6leot6si1si6mou6so2"],
["大律師的收費","counsel's fees / 大律师的收费 / dà lǜ shī de shōu fèi / daai6leot6si1dik1sau1fai3"],
["大律師書記","barrister's clerk / 大律师书记 / dà lǜ shī shū ji / daai6leot6si1syu1gei3"],
["大律師登記冊","roll of barristers / 大律师登记册 / dà lǜ shī dēng jì cè / daai6leot6si1dang1gei3caak3"],
["大赦","amnesty / 大赦 / dà shè / daai6se3"],
["天災","act of God / 天灾 / tiān zāi / tin1zoi1"],
["太平紳士","/justice/justice of peace/ / 太平绅士 / tài píng shēn shì / taai3ping4san1si2"],
["夫妾關係","union of concubinage / 夫妾关系 / fū qiè guān xi / fu1cip3gwaan1hai6"],
["夫妾關係中的子女","a child of a union of concubinage / 夫妾关系中的子女 / fū qiè guān xi zhòng dì zǐ nǚ / fu1cip3gwaan1hai6zung1dik1zi2neoi5"],
["失去時效","lapse / 失去时效 / shī qù shí xiào / sat1 heoi3 si4 haau6"],
["失效","/avoided/expire/lapse/  / 失效 / shī xiào / sat1 haau6"],
["失責","default / 失责 / shī zé / sat1 zaak3"],
["失責者","defaulter / 失责者 / shī zé zhĕ / sat1 zaak3 ze2"],
["失責處理規則","default rules / 失责处理规则 / shī zé chŭ lĭ guī zé / sat1 zaak3 cyu3 lei5 kwai1 zak1"],
["失責處理程序","default proceedings / 失责处理程序 / shī zé chŭ lĭ chéng xù / sat1 zaak3 cyu3 lei5 cing4 zeoi6"],
["失責罰款","default fine / 失责罚款 / shī zé fá kuăn / sat1 zaak3 fat6 fun2"],
["失實","untrue / 失实 / shī shí / sat1 sat6"],
["失實陳述","misrepresentation / 失实陈述 / shī shí chén shù / sat1 sat6 can4 seot6"],
["失職行為","breach of duty / 失职行为 / shī zhí xíng wéi / sat1 zik1 hang4 wai4"],
["子女撫卹金","children's pension / 子女抚恤金 / zǐ nǚ fǔ xù jīn / zi2neoi5fu2seot1gam1"],
["子民與子民之間的訴訟","action between subjects / 子民与子民之间的诉讼 / zǐ mín yǔ zǐ mín zhī jiān de sù sòng / zi2man4ju5zi2man4zi1gaan1/gaan3dik1sou3zung6"],
["存款證","certificate of deposit / 存款证 / cún kuăn zhèng / cyun4 fun2 zing3"],
["小股東控權人","minority shareholder controller / 小股东控权人 / xiǎo gǔ dōng kòng quán rén / siu2gu2dung1hung3kyun4jan4"],
["小組","panel / 小组 / xiǎo zǔ / siu2zou2"],
["小組委員會","committee / 小组委员会 / xiǎo zǔ wěi yuán huì / siu2zou2wai2jun4wui2"],
["小額錢債審裁處","Small Claims Tribunal / 小额钱债审裁处 / xiǎo é qián zhài shěn cái chǔ / siu2ngaak6cin4zaai3sam2coi4cyu5"],
["小額錢債審裁處訴訟人儲存金帳戶","Small Claims Tribunal Suitors' Funds Account / 小额钱债审裁处诉讼人储存金帐户 /  xiǎo é qián zhài shěn cái chǔ sù sòng rén chǔ cún jīn zhàng hù  / siu2ngaak6cin4zaai3sam2coi4cyu5sou3zung6jan4cyu5cyun4gam1zoeng3wu6"],
["小額薪酬索償仲裁處","Minor Employment Claims Adjudication Board / 小额薪酬索偿仲裁处 / xiǎo é xīn chóu suǒ cháng zhòng cái chù / siu2ngaak6san1cau4sok3soeng4zung6coi4cyu5"],
["少年","juvenile / 少年 / shào nián / siu3nin4"],
["少年人","young person / 少年人 / shào nián rén / siu3nin4jan4"],
["少年犯人","juvenile offender / 少年犯人 / shào nián fàn rén / siu3nin4faan6jan4"],
["少年法庭","juvenile court / 少年法庭 / shào nián fǎ tíng / siu3nin4faat3ting4"],
["少年罪犯","young offenders / 少年罪犯 / shào nián zuì fàn / siu3nin4zeoi6faan6"],
["少年罪犯","youthful offender / 少年罪犯 / shào nián zuì fàn / siu3nin4zeoi6faan6"],
["少數權益","minority interests / 少数权益 / shǎo shù quán yì / siu2sou3/sou2kyun4jik1"],
["工作天","/business day/working day/ / 工作天 / gōng zuò tiān / gung1zok3tin1"],
["工作日","working day / 工作日 / gōng zuò rì / gung1zok3jat6"],
["工作守則","code of practice / 工作守则 / gōng zuò shǒu zé / gung1zok3sau2zak1"],
["工傷","industrial injury / 工伤 / gōng shāng / gung1soeng1"],
["工傷導致傷殘","industrial disablement / 工伤导致伤残 / gōng shāng dǎo zhì shāng cán / gung1soeng1dou6zi3soeng1caan4"],
["工業知識","know-how / 工业知识 / gōng yè zhī shi / gung1jip6zi1sik1"],
["工業知識的權利","rights to know-how / 工业知识的权利 / gōng yè zhī shi de quán lì / gung1jip6zi1sik1dik1kyun4lei6"],
["工資","wages / 工资 / gōng zī / gung1zi1"],
["已完稅貨品","duty-paid goods / 已完税货品 / yǐ wán shuì huò pǐn / ji5jun4seoi3fo3ban2"],
["已屆成年","of age / 已届成年 / yǐ jiè chéng nián / ji5gaai3sing4nin4"],
["已屆成年並具行為能力","of full age and capacity / 已届成年并具行为能力 / yǐ jiè chéng nián bìng jù xíng wéi néng lì / ji5gaai3sing4nin4bing6geoi6hang4wai4nang4lik6"],
["已拒付匯票的參加承兌","acceptance for honour suprá protest / 已拒付汇票的参加承兑 / yǐ jù fù huì piào de cān jiā chéng duì / ji5keoi5fu6wui6piu3dik1caam1gaa1sing4deoi3"],
["已採取所有合理的預防措施","took all reasonable precautions / 已采取所有合理的预防措施 / yǐ cǎi qǔ suǒ yǒu hé lǐ de yù fáng cuò shī / ji5coi2ceoi2so2jau5hap6lei5dik1ju6fong4cou3si1"],
["已提供付款的訴","plea of tender / 已提供付款的诉 / yǐ tí gōng fù kuǎn de sù / ji5tai4gung1fu6fun2dik1sou3"],
["已登記所有人","registered proprietors / 已登记所有人 / yǐ dēng jì suǒ yǒu rén / ji5dang1gei3so2jau5jan4"],
["已登記押記","registered charge / 已登记押记 / yǐ dēng jì yā jì / ji5dang1gei3aat3gei3"],
["已登記職工會聯會","registered trade union federation / 已登记职工会联会 / yǐ dēng jì zhí gōng huì lián huì / ji5dang1gei3zik1gung1wui2lyun4wui2"],
["已進行部分聆訊","part-heard / 已进行部分聆讯 / yǐ jìn xíng bù fen líng xùn / ji5zeon3hang4bou6fan6ling4seon3"],
["已過時的條例","obsolete Ordinances / 已过时的条例 / yǐ guò shí de tiáo lì / ji5gwo3si4dik1tiu4lai6"],
["已繳足股款的股份","fully paidup shares / 已缴足股款的股份 / yǐ jiǎo zú gǔ kuǎn de gǔ fèn / ji5giu2zuk1gu2fun2dik1gu2fan6"],
["已證明債權的債權人","creditor who has proved his debt / 已证明债权的债权人 / yǐ zhèng míng zhài quán de zhài quán rén / ji5zing3ming4zaai3kyun4dik1zaai3kyun4jan4"],
["市政府","municipality / 市政府 / shì zhèng fŭ / si5 zing3 fu2"],
["市值租金","prevailing market rent / 市值租金 / shì zhí zū jīn / si5 zik6 zou1 gam1"],
["市區重建","urban renewal / 市区重建 / shì qū chóng jiàn / si5 keoi1 cung4 gin3"],
["市場合約","market contract / 市场合约 / shì chăng hé yuē / si5 coeng4 hap6 joek3"],
["市場抵押品","market collateral / 市场抵押品 / shì chăng dĭ yā pĭn / si5 coeng4 dai2 aat3 ban2"],
["市價中位數","middle market price / 市价中位数 / shì jià zhōng wèi shù / si5 gaa3 zung1 wai2 sou3"],
["市議會","municipal council / 市议会 / shì yì huì / si5 ji5 wui2"],
["干預","/intervention/tamper with/ / 干预 / gān yù / gon1ju6"],
["干擾","/disturb/interfere/tampered/ / 干扰 / gān rǎo / gon1jiu2"],
["干擾證人","interfere with a witness / 干扰证人 / gān rǎo zhèng ren / gon1jiu2zing3jan4"],
["引渡","extradite / 引渡 / yǐn dù / jan5dou6"],
["引渡法律程序","extradition proceedings / 引渡法律程序 / yǐn dù fǎ lǜ chéng xù / jan5dou6faat3leot6cing4zeoi6"],
["引渡條約","extradition treaty / 引渡条约 / yǐn dù tiáo yuē / jan5dou6tiu4joek3"],
["引渡程序","extradition proceedings / 引渡程序 / yǐn dù chéng xù / jan5dou6cing4zeoi6"],
["心智上無行為能力","mental incapacity / 心智上无行为能力 / xīn zhì shàng wú xíng wéi néng lì / sam1zi3soeng6mou4hang4wai4nang4lik6"],
["心智發育停頓或不完全","arrested or incomplete development of mind / 心智发育停顿或不完全 / xīn zhì fā yù tíng dùn huò bù wán quán / sam1zi3faat3juk6ting4deon6waak6bat1jun4cyun4"],
["心智發育遲緩","retarded development of mind / 心智发育迟缓 / xīn zhì fā yù chí huǎn / sam1zi3faat3juk6ci4wun6"],
["必然含義","necessary implication / 必然含义 / bì rán hán yì / bit1 jin4 ham4 ji6"],
["必然推論","necessary inference / 必然推论 / bì rán tuī lùn / bit1 jin4 teoi1 leon6"],
["手令","warrant / 手令 / shǒu lìng / sau2ling6"],
["手令上的批註","endorsement on the warrant / 手令上的批注 / shǒu lìng shàng de pī zhù / sau2ling6soeng6dik1pai1zyu3"],
["手續","procedure / 手续 / shŏu xù / sau2 zuk6"],
["打擾","disturbance / 打扰 / dă răo / daa2 jiu2"],
["扣押物","distress / 扣押物 / kòu yā wù / kau3 aat3 mat6"],
["扣押財物","distraint / 扣押财物 / kòu yā cái wù / kau3 aat3 coi4 mat6"],
["扣押通知","notice of seizure / 扣押通知 / kòu yā tōng zhī / kau3 aat3 tung1 zi1"],
["支付訟費命令","an order for costs / 支付讼费命令 / zhī fù sòng fèi mìng lìng / zi1 fu6 zung6 fai3 ming6 ling6"],
["支持文件","supporting documents / 支持文件 / zhī chí wén jiàn / zi1 ci4 man4 gin6"],
["收支表","income and expenditure account / 收支表 / shōu zhī biăo / sau1 zi1 biu2"],
["收市價","closing price / 收市价 / shōu shì jià / sau1 si5 gaa3"],
["收回土地","resumption of land / 收回土地 / shōu huí tŭ di / sau1 wui4 tou2 dei6"],
["收回管有","recovery of possession / 收回管有 / shōu huí guăn yŏu / sau1 wui4 gun2 jau5"],
["收受贓物","receiving stolen property / 收受赃物 / shōu shòu zāng wù / sau1 sau6 zong1 mat6"],
["收容所","place of refuge / 收容所 / shōu róng suŏ / sau1 jung4 so2"],
["收購","/acquisition/take-over/ / 收购 / shōu gòu / sau1 kau3"],
["文本","/copy/text/ / 文本 / wén bĕn / man4 bun2"],
["文件","document / 文件 / wén jiàn / man4 gin6"],
["文件清單","lists of documents / 文件清单 / wén jiàn qīng dān / man4 gin6 cing1 daan1"],
["文件透露","discovery of documents / 文件透露 / wén jiàn tòu lù / man4 gin6 tau3 lou6"],
["文件證物","documentary exhibits / 文件证物 / wén jiàn zhèng wù / man4 gin6 zing3 mat6"],
["文字商標","word trade mark / 文字商标 / wén zì shāng biāo / man4 zi6 soeng1 biu1"],
["文告","proclamation / 文告 / wén gào / man4 gou3"],
["文書","instrument / 文书 / wén shū / man4 syu1"],
["文書錯誤","clerical mistakes / 文书错误 / wén shū cuò wù / man4 syu1 co3 ng6"],
["方","party / 方 / fāng / fong1"],
["方案","plan / 方案 / fāng àn / fong1 ngon3"],
["日內瓦各項公約","Geneva Conventions / 日内瓦各项公约 / rì nèi wă gè xiàng gōng yuē / jat6 noi6 ngaa5 gok3 hong6 gung1 joek3"],
["有限法律責任","limited liability / 有限法律责任 / yŏu xiàn fă lǜ zé rèn / jau5 haan6 faat3 leot6 zaak3 jam6"],
["有效執業證書","current practising certificate / 有效执业证书 / yŏu xiào zhí yè zhèng shū / jau5 haau6 zap1 jip6 zing3 syu1"],
["有效證明書","certificate of validity / 有效证明书 / yŏu xiào zhèng míng shū / jau5 haau6 zing3 ming4 syu1"],
["有期徒刑","determinate sentence / 有期徒刑 / yŏu qī tú xíng / jau5 kei4 tou4 jing4"],
["有罪裁決","verdict of guilty / 有罪裁决 / yŏu zuì cái jué / jau5 zeoi6 coi4 kyut3"],
["未成年人的監護人","guardian of minor / 未成年人的监护人 / wèi chéng nián rén de jiān hù rén / mei6 sing4 nin4 jan4 dik1 gaam1 wu6 jan4"],
["未成年人財產監護人","guardian of the property of infants / 未成年人财产监护人 / wèi chéng nián rén cái chăn jiān hù rén / mei6 sing4 nin4 jan4 coi4 caan2 gaam1 wu6 jan4"],
["未成年人權益","minority interest / 未成年人权益 / wèi chéng nián rén quán yì / mei6 sing4 nin4 jan4 kyun4 jik1"],
["未成年子女","minor child / 未成年子女 / wèi chéng nián zĭ nǚ / mei6 sing4 nin4 zi2 neoi5"],
["未批租土地","unleased land / 未批租土地 / wèi pī zū tŭ di / mei6 pai1 zou1 tou2 dei6"],
["未決申索","claims outstanding / 未决申索 / wèi jué shēn suŏ / mei6 kyut3 san1 sok3"],
["未決算法律責任","unliquidated liabilities / 未决算法律责任 / wèi jué suàn fă lǜ zé rèn / mei6 kyut3 syun3 faat3 leot6 zaak3 jam6"],
["未來有效的權益","executory interest / 未来有效的权益 / wèi lái yŏu xiào de quán yì / mei6 loi4 jau5 haau6 dik1 kyun4 jik1"],
["未來版權","future copyright / 未来版权 / wèi lái băn quán / mei6 loi4 baan2 kyun4"],
["未來產業權","future estate / 未来产业权 / wèi lái chăn yè quán / mei6 loi4 caan2 jip6 kyun4"],
["未來權益的持有人","remainderman / 未来权益的持有人 / wèi lái quán yì de chí yŏu rén / mei6 loi4 kyun4 jik1 dik1 ci4 jau5 jan4"],
["未發行股份","unissued shares / 未发行股份 / wèi fā xíng gŭ fèn / mei6 faat3 hang4 gu2 fan6"],
["未經授權的作為","unauthorized act / 未经授权的作为 / wèi jīng shòu quán de zuò wéi / mei6 ging1 sau6 kyun4 dik1 zok3 wai4"],
["未經註冊商標","unregistered trade mark / 未经注册商标 / wèi jīng zhù cè shāng biāo / mei6 ging1 zyu3 caak3 soeng1 biu1"],
["未過期風險","unexpired risks / 未过期风险 / wèi guò qī fēng xiăn / mei6 gwo3 kei4 fung1 him2"],
["未審決","depending / 未审决 / wèi shĕn jué / mei6 sam2 kyut3"],
["本土法律","internal law / 本土法律 / bĕn tŭ fă lǜ / bun2 tou2 faat3 leot6"],
["本地代理人","local agent / 本地代理人 / bĕn dì dài lĭ rén / bun2 dei6 doi6 lei5 jan4"],
["本地仲裁協議","domestic arbitration agreement / 本地仲裁协议 / bĕn dì zhòng cái xié yì / bun2 dei6 zung6 coi4 hip3 ji5"],
["本地合格證書","local certificate of competency / 本地合格证书 / bĕn dì hé gé zhèng shū / bun2 dei6 hap6 gaak3 zing3 syu1"],
["本地承付票","inland note / 本地承付票 / bĕn dì chéng fù piào / bun2 dei6 sing4 fu6 piu3"],
["本國法律","national law / 本国法律 / bĕn guó fă lǜ / bun2 gwok3 faat3 leot6"],
["本部領域","metropolitan territory / 本部领域 / bĕn bù lĭng yù / bun2 bou6 ling5 wik6"],
["本訴","principal claim / 本诉 / bĕn sù / bun2 sou3"],
["本籍","domicile / 本籍 / bĕn jí / bun2 zik6"],
["村代表","village representative / 村代表 / cūn dài biăo / cyun1 doi6 biu2"],
["欠妥","defect / 欠妥 / qiàn tuŏ / him3 to5"],
["欠缺抗辯書","in default of defence / 欠缺抗辩书 / qiàn quē kàng biàn shū / him3 kyut3 kong3 bin6 syu1"],
["欠缺所有權","want of title / 欠缺所有权 / qiàn quē suŏ yŏu quán / him3 kyut3 so2 jau5 kyun4"],
["欠缺狀書","in default of pleading / 欠缺状书 / qiàn quē zhuàng shū / him3 kyut3 zong6 syu1"],
["欠缺真誠","want of good faith / 欠缺真诚 / qiàn quē zhēn chéng / him3 kyut3 zan1 sing4"],
["欠款證明書","certificate of arrears / 欠款证明书 / qiàn kuăn zhèng míng shū / him3 fun2 zing3 ming4 syu1"],
["欠繳","default of payment / 欠缴 / qiàn jiăo / him3 giu2"],
["止贖","foreclosure / 止赎 / zhĭ shú / zi2 suk6"],
["止贖權","right to foreclose / 止赎权 / zhĭ shú quán / zi2 suk6 kyun4"],
["止贖訴訟","foreclosure action / 止赎诉讼 / zhĭ shú sù sòng / zi2 suk6 sou3 zung6"],
["正式判決","formal judgment / 正式判决 / zhèng shì pàn jué / zing3 sik1 pun3 kyut3"],
["正式指示","official direction / 正式指示 / zhèng shì zhĭ shì / zing3 sik1 zi2 si6"],
["正式查訊","official inquiry / 正式查讯 / zhèng shì chá xùn / zing3 sik1 caa4 seon3"],
["正式會員","/corporate member/full member/ / 正式会员 / zhèng shì huì yuán / zing3 sik1 wui2 jyun4"],
["正式會員資格","corporate membership / 正式会员资格 / zhèng shì huì yuán zī gé / zing3 sik1 wui2 jyun4 zi1 gaak3"],
["正式認知","officially noticed / 正式认知 / zhèng shì rèn zhī / zing3 sik1 jing6 zi1"],
["正妻","principal wife / 正妻 / zhèng qī / zing3 cai1"],
["正規武裝部隊","regular armed forces / 正规武装部队 / zhèng guī wŭ zhuāng bù duì / zing3 kwai1 mou5 zong1 bou6 deoi6"],
["正當懷疑","justifiable doubts / 正当怀疑 / zhèng dàng huái yí / zing3 dong1 waai4 ji4"],
["死亡研訊","death inquiries / 死亡研讯 / sĭ wáng yán xùn / sei2 mong4 jin4 seon3"],
["死因檢驗","post-mortem examination / 死因检验 / sĭ yīn jiăn yàn / sei2 jan1 gim2 jim6"],
["母公司","holding company / 母公司 / mŭ gōng sī / mou5 gung1 si1"],
["比例代表名單制","the list system of proportional representation / 比例代表名单制 / bĭ lì dài biăo míng dān zhì / bei2 lai6 doi6 biu2 ming4 daan1 zai3"],
["比例代表原則","principle of proportionate representation / 比例代表原则 / bĭ lì dài biăo yuán zé / bei2 lai6 doi6 biu2 jyun4 zak1"],
["民事上訴案","civil appeals / 民事上诉案 / mín shì shàng sù àn / man4 si6 soeng5 sou3 ngon3"],
["民事司法管轄權","civil jurisdiction / 民事司法管辖权 / mín shì sī fă guăn xiá quán / man4 si6 si1 faat3 gun2 hat6 kyun4"],
["民事申索","civil claim / 民事申索 / mín shì shēn suŏ / man4 si6 san1 sok3"],
["民事法律責任","civil liability / 民事法律责任 / mín shì fă lǜ zé rèn / man4 si6 faat3 leot6 zaak3 jam6"],
["民事法律程序","/civil proceedings/civil procedure/ / 民事法律程序 / mín shì fă lǜ chéng xù / man4 si6 faat3 leot6 cing4 zeoi6"],
["民事法庭","civil court / 民事法庭 / mín shì fă tíng / man4 si6 faat3 ting4"],
["民事案件","civil matters / 民事案件 / mín shì àn jiàn / man4 si6 ngon3 gin6"],
["民事起訴","civil suit / 民事起诉 / mín shì qĭ sù / man4 si6 hei2 sou3"],
["民事訟案","civil cause / 民事讼案 / mín shì sòng àn / man4 si6 zung6 ngon3"],
["民事責任制度","civil liability regime / 民事责任制度 / mín shì zé rèn zhì dù / man4 si6 zaak3 jam6 zai3 dou6"],
["民事補救","civil remedy / 民事补救 / mín shì bŭ jiù / man4 si6 bou2 gau3"],
["民事訴訟","civil action / 民事诉讼 / mín shì sù sòng / man4 si6 sou3 zung6"],
["民事債項","civil debt / 民事债项 / mín shì zhài xiàng / man4 si6 zaai3 hong6"],
["民事過失","civil wrong / 民事过失 / mín shì guò shī / man4 si6 gwo3 sat1"],
["民事審訊","civil trial / 民事审讯 / mín shì shĕn xùn / man4 si6 sam2 seon3"],
["民事權利","civil right / 民事权利 / mín shì quán lì / man4 si6 kyun4 lei6"],
["水務監督","Water Authority / 水务监督 / shuĭ wù jiān dū / seoi2 mou6 gaam1 duk1"],
["水域","territorial sea / 水域 / shuĭ yù / seoi2 wik6"],
["永久形式誹謗","libel / 永久形式诽谤 / yŏng jiŭ xíng shì fĕi bàng / wing5 gau2 jing4 sik1 fei2 pong3"],
["永久居留地","permanent residence / 永久居留地 / yŏng jiŭ jū liú dì / wing5 gau2 geoi1 lau4 dei6"],
["永久延續","perpetual succession / 永久延续 / yŏng jiŭ yán xù / wing5 gau2 jin4 zuk6"],
["永久性居民","permanent resident / 永久性居民 / yŏng jiŭ xìng jū mín / wing5 gau2 sing3 geoi1 man4"],
["永久性居民身分證","permanent identity card / 永久性居民身分证 / yŏng jiŭ xìng jū mín shēn fèn zhèng / wing5 gau2 sing3 geoi1 man4 san1 fan1 zing3"],
["永久性傷害","permanent injury / 永久性伤害 / yŏng jiŭ xìng shāng hài / wing5 gau2 sing3 soeng1 hoi6"],
["永久後償債項","perpetual subordinated debt / 永久后偿债项 / yŏng jiŭ hòu cháng zhài xiàng / wing5 gau2 hau6 soeng4 zaai3 hong6"],
["永久強制令","perpetual injunction / 永久强制令 / yŏng jiŭ qiáng zhì lìng / wing5 gau2 koeng4 zai3 ling6"],
["永久產權","fee simple / 永久产权 / yŏng jiŭ chăn quán / wing5 gau2 caan2 kyun4"],
["永久無能力","permanent incapacity / 永久无能力 / yŏng jiŭ wú néng lì / wing5 gau2 mou4 nang4 lik6"],
["永久業權","permanent title / 永久业权 / yŏng jiŭ yè quán / wing5 gau2 jip6 kyun4"],
["火器","firearm / 火器 / huŏ qì / fo2 hei3"],
["火險","fire insurance / 火险 / huŏ xiăn / fo2 him2"],
["火警危險令","fire hazard order / 火警危险令 / huŏ jĭng wēi xiăn lìng / fo2 ging2 ngai4 him2 ling6"],
["父母權利","parental rights  / 父母权利 / fù mŭ quán lì / fu6 mou5 kyun4 lei6"],
["父系","male line / 父系 / fù xì / fu6 hai6"],
["犯人欄","bar / 犯人栏 / fàn rén lán / faan6 jan4 laan4"],
["犯事者","offender / 犯事者 / fàn shì zhĕ / faan6 si6 ze2"],
["犯法","commits an offence / 犯法 / fàn fă / faan6 faat3"],
["犯罪元素","element of the offence  / 犯罪元素 / fàn zuì yuán sù / faan6 zeoi6 jyun4 sou3"],
["犯罪目的","criminal purpose / 犯罪目的 / fàn zuì mù dì / faan6 zeoi6 muk6 dik1"],
["犯罪得益","proceeds of crime / 犯罪得益 / fàn zuì dé yì / faan6 zeoi6 dak1 jik1"],
["生父","natural father / 生父 / shēng fù / saang1 fu6"],
["生活費","alimony / 生活费 / shēng huó fèi / saang1 wut6 fai3"],
["生效","/alimony/valid/ / 生效 / shēng xiào / saang1 haau6"],
["生效日期","/date of commencement/effective day/ / 生效日期 / shēng xiào rì qī / saang1 haau6 jat6 kei4"],
["申索人","claimant / 申索人 / shēn suŏ rén / san1 sok3 jan4"],
["申索毛額","gross claims / 申索毛额 / shēn suŏ máo é / san1 sok3 mou4 ngaak6"],
["申索通知","notice of claim / 申索通知 / shēn suŏ tōng zhī / san1 sok3 tung1 zi1"],
["申索陳述書","statement of claim / 申索陈述书 / shēn suŏ chén shù shū / san1 sok3 can4 seot6 syu1"],
["申報人","informant / 申报人 / shēn bào rén / san1 bou3 jan4"],
["申訴","complaint / 申诉 / shēn sù / san1 sou3"],
["申訴人","complainant / 申诉人 / shēn sù rén / san1 sou3 jan4"],
["申訴理由","ground of complaint / 申诉理由 / shēn sù lĭ yóu / san1 sou3 lei5 jau4"],
["申請人","applicant / 申请人 / shēn qĭng rén / san1 cing2 jan4"],
["申辯","/plea/plead / 申辩 / shēn biàn / san1 bin6"],
["目的國","country of destination / 目的国 / mù dì guó / muk6 dik1 gwok3"],
["目視檢查","visual inspection / 目视检查 / mù shì jiăn chá / muk6 si6 gim2 caa4"],
["立法效力","legislative effect / 立法效力 / lì fă xiào lì / lap6 faat3 haau6 lik6"],
["立法會","Legislative Council / 立法会 / lì fă huì / lap6 faat3 wui2"],
["立法機關","Legislature / 立法机关 / lì fă jī guān / lap6 faat3 gei1 gwaan1"],
["立遺囑人","testator / 立遗嘱人 / lì yí zhŭ rén / lap6 wai4 zuk1 jan4"],
["立遺囑人遺願","testamentary intentions / 立遗嘱人遗愿 / lì yí zhŭ rén yí yuàn / lap6 wai4 zuk1 jan4 wai4 jyun6"],
["A","B"]
];

function a2b(){
document.aba.B.value="";
for (i=0; i<abList.length; i++)
  if(document.aba.A.value==abList[i][0])
    {document.aba.B.value=document.aba.B.value + abList[i][1] + "/";};

if(document.aba.B.value=="")
  document.aba.B.value="Not found.";
else
  document.aba.B.value=document.aba.B.value.substr(0,document.aba.B.value.length-1); //delete the fianl slash.
}

function b2a(){
document.aba.A.value="";
for (i=0; i<abList.length; i++)
if(document.aba.B.value==abList[i][1])
{document.aba.A.value=document.aba.A.value + abList[i][0] + "/";};
if(document.aba.A.value=="")
{document.aba.A.value="Not found";}
else
  document.aba.A.value=document.aba.A.value.substr(0,document.aba.A.value.length-1); //delete the fianl slash.
}

</script>

<style>

body {color: tomato; background-color: #FFF5F0; font-family:"times new roman";}
h2 {color: tomato; font-family: script}
h4 {color: black; font-family: script}
.aa {color: pink; font-size: 150%;}
</style>

</head>

<body>

<div class="aa"> *********************************************************************************************************************** </div>

<h2>Chinese-English Legal Dictionary Interactive Version</h2> 
<h4>Please type in the words you want to search.</h4>
<br />
<img src="https://travel.state.gov/content/travel/en/legal/_jcr_content/tsg-rwd-content-page-parsys/slideshow.img.jpg/1512169201172.jpg" />
<br />
<br />
<br />
<br />
<form name="aba">
Chinese entry: <input type="text" name="A" size="80"> 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<input type="button" name="A2B" value=translate onClick="a2b()">
<br />
<br />
<br />
English definition, Simplified Chinese, Pinyin & Jyutping: <input type="text" name="B" size="200">

<br />
</form>

<br />
<br />
<br />
<br />
<br />
<br />
<div class="aa"> *********************************************************************************************************************** </div>

</body>
</html>
